In [1]:
import pandas as pd

In [2]:
train = pd.read_csv('train.csv', index_col = 0)
train.head()

              y1         y2        y3         y4
x
-20.0  19.794191 -40.422230  1.089534  409.53973
-19.9  19.808426 -40.516800  0.800835  405.70517
-19.8  19.915476 -39.584960  1.095554  401.80957
-19.7  19.715796 -39.989166  1.161140  397.87543
-19.6  19.642672 -39.418360  0.365370  394.22790

In [3]:
train.tail(10)

             y1         y2        y3         y4
x
19.0  19.229618  38.311530  0.077070  371.15436
19.1  19.368603  38.822636  0.022189  374.86356
19.2  18.984886  38.404570 -0.420213  378.85876
19.3  19.171904  38.674915 -0.702113  382.74152
19.4  19.178747  38.805237 -0.531154  386.68387
19.5  19.450926  39.161300 -0.482247  390.46017
19.6  19.944368  39.720966 -1.082964  393.94876
19.7  20.189590  39.817450 -0.425631  397.94064
19.8  19.973238  39.968720 -1.074738  402.41840
19.9  19.593924  39.922030 -0.868087  405.54385

In [4]:
import sqlite3

In [5]:
dbname = 'train.db'

conn = sqlite3.connect(dbname)
cur = conn.cursor()

In [6]:
train.to_sql('sample', conn, if_exists = 'replace')

select_sql = 'SELECT * FROM sample'
for row in cur.execute(select_sql):
    print(row)

cur.close()
conn.close()

(-20.0, 19.794191, -40.42223, 1.089534, 409.53972999999996)
(-19.9, 19.808426, -40.5168, 0.8008345, 405.70517)
(-19.8, 19.915476, -39.584959999999995, 1.0955542, 401.80957)
(-19.7, 19.715795999999997, -39.989166, 1.1611403999999999, 397.87543)
(-19.6, 19.642672, -39.41836, 0.36537006, 394.2279)
(-19.5, 20.08945, -38.879887, 0.84317005, 390.55368)
(-19.4, 19.814774, -39.066986, 0.6643654, 386.5699)
(-19.3, 19.566328, -38.455597, -0.05420668, 382.52932999999996)
(-19.2, 19.61658, -38.84663, 0.5915438000000001, 378.70245)
(-19.1, 19.16017, -38.740612, 0.0732244, 374.957)
(-19.0, 18.925045, -38.345284, -0.28477514, 370.95867999999996)
(-18.9, 19.205929, -37.53655, -0.2005006, 367.34265)
(-18.8, 19.152414, -37.867954, -0.21227016, 363.29733)
(-18.7, 18.778013, -36.971306, 0.068578154, 359.8606)
(-18.6, 18.648546, -37.341652, 0.016525472, 355.75345)
(-18.5, 19.094023, -36.59465, -0.49281928, 352.3205)
(-18.4, 18.948207999999997, -36.54647, -0.51808435, 348.56528)
(-18.3, 18.43834, -36.414246, -0.45694578, 344.84015)
(-18.2, 17.865054999999998, -36.305541999999996, -0.17177707, 341.04553)
(-18.1, 18.014805, -36.339455, -0.4125805, 338.0818)
(-18.0, 18.49015, -35.64176, -0.33301133, 334.49277)
(-17.9, 17.642826, -35.342777000000005, -1.1598275, 330.62827000000004)
(-17.8, 18.280615, -35.655457, -0.71870786, 326.51874)
(-17.7, 17.901152, -34.657515999999994, -0.5032418, 323.62326)
(-17.6, 17.788818, -35.068020000000004, -1.3496113, 320.07532000000003)
(-17.5, 17.432823000000003, -34.9385, -0.7039151, 316.60977)
(-17.4, 17.781370000000003, -34.242909999999995, -0.5064758, 313.21808)
(-17.3, 17.252438, -34.540490000000005, -1.2424662, 309.5064)
(-17.2, 17.841944, -34.05583, -1.2674836, 305.54034)
(-17.1, 17.175444, -34.048843, -0.7119941, 302.00327000000004)
(-17.0, 17.400875, -33.115746, -0.50377613, 298.9917)
(-16.9, 17.00539, -33.65461, -0.9515665000000001, 295.25142999999997)
(-16.8, 17.147802, -32.851096999999996, -0.86829334, 292.57956)
(-16.7, 16.763479999999998, -32.840509999999995, -0.7551585999999999, 289.09738)
(-16.6, 16.416929999999997, -33.061863, -0.74103373, 285.69922)
(-16.5, 16.578556, -32.624443, -0.6803229000000001, 282.41714)
(-16.4, 16.351282, -32.428309999999996, -0.8478377, 279.21502999999996)
(-16.3, 16.108294, -32.027397, -0.8004009, 275.9046)
(-16.2, 16.639622, -32.137722, -0.7449937, 272.77783)
(-16.1, 16.526445000000002, -31.628140000000002, 0.07725865400000001, 269.21466000000004)
(-16.0, 16.485176, -31.657890000000002, -0.17993829999999997, 265.90982)
(-15.9, 15.990962, -32.088768, -0.6379058000000001, 262.43115)
(-15.8, 15.653673999999999, -31.34132, 0.3015339, 259.43393)
(-15.7, 15.653441, -31.708340000000003, 0.30715057, 256.71417)
(-15.6, 15.816272, -30.851963, 0.5935541999999999, 253.15039)
(-15.5, 15.527826999999998, -31.582209000000002, -0.27703792, 250.46432000000001)
(-15.4, 15.172101000000001, -31.290940999999997, 0.14668874, 246.9336)
(-15.3, 15.76198, -30.932346000000003, 0.108139955, 244.07733)
(-15.2, 15.317689000000001, -30.21725, 0.74587643, 241.2969)
(-15.1, 15.702274, -30.203004999999997, 0.7596576999999999, 237.61012000000002)
(-15.0, 15.400194, -30.521942, 0.9563520000000001, 234.85619)
(-14.9, 15.41707, -29.746328000000002, 0.5591083, 231.73012999999997)
(-14.8, 15.386884, -29.844763, 0.9750610000000001, 229.23904)
(-14.7, 14.8361225, -30.164790999999997, 0.47950333, 226.02687000000003)
(-14.6, 14.801023999999998, -29.65345, 0.58147526, 222.88282999999998)
(-14.5, 14.600244, -29.221676000000002, 0.7160904, 220.03522)
(-14.4, 14.278887, -29.423496000000004, 1.1993375, 216.89853)
(-14.3, 14.747829999999999, -29.133257, 1.3285023999999999, 214.55017)
(-14.2, 14.170936, -28.883245000000002, 1.1341695, 211.40965)
(-14.1, 14.209151, -28.510258, 0.5375770999999999, 208.81548)
(-14.0, 14.018475, -28.922521999999997, 1.3921558, 205.75351)
(-13.9, 14.421428, -28.134285, 1.3206426000000002, 203.43835)
(-13.8, 13.648276999999998, -27.610704, 1.0470963, 200.83221)
(-13.7, 13.659695000000001, -28.258314000000002, 0.46921882, 198.1619)
(-13.6, 14.012806, -27.711882, 1.0425434999999998, 194.75208999999998)
(-13.5, 13.280728, -27.448933, 0.72990286, 192.61737)
(-13.4, 13.09564, -27.22632, 0.7852293, 189.07967)
(-13.3, 13.820897, -27.304503999999998, 0.8654054, 186.99168)
(-13.2, 13.659145, -26.586067, 0.31173486, 183.97006000000002)
(-13.1, 13.650429, -26.105895999999998, 0.69717234, 181.70245)
(-13.0, 13.358913000000001, -25.838188, 0.571407, 179.00127)
(-12.9, 13.008151, -26.052335999999997, 0.38388088, 176.79549)
(-12.8, 13.336504999999999, -25.360661999999998, 0.20996092, 173.92969)
(-12.7, 13.083289, -25.016428, 0.099197045, 171.34900000000002)
(-12.6, 13.193595000000002, -24.98613, -0.38749442, 168.9372)
(-12.5, 12.360685, -24.855686, -0.27927113, 166.01703999999998)
(-12.4, 12.6118355, -24.643385000000002, 0.0633778, 163.86792)
(-12.3, 12.219076, -24.551493, 0.21272932, 161.76273999999998)
(-12.2, 12.855024, -24.557806, -0.81291825, 158.59253999999999)
(-12.1, 12.290515, -24.45293, -0.9350189, 156.71222)
(-12.0, 11.741588, -23.321522, -0.35034463, 153.63249)
(-11.9, 11.733461, -23.296778, -0.8694023000000001, 151.99586000000002)
(-11.8, 11.971921, -23.281826000000002, -0.21453674, 149.46483999999998)
(-11.7, 12.0472355, -22.916706, -1.1511141000000003, 147.31802)
(-11.6, 12.226347, -22.799204, -1.0595754, 144.48013)
(-11.5, 11.804474, -22.194733, -1.3170986, 142.38593)
(-11.4, 11.622264, -22.319841, -1.1580153999999998, 139.51546000000002)
(-11.3, 11.991512, -22.564182000000002, -0.74742156, 137.61467)
(-11.2, 11.432112, -22.277758, -1.4764177, 135.47533)
(-11.1, 11.280842999999999, -21.94386, -1.3080559999999999, 133.43079)
(-11.0, 11.234173, -21.847611999999998, -1.0786208000000002, 130.71413)
(-10.9, 11.197855, -20.946207, -0.96898013, 128.78201)
(-10.8, 11.454589, -20.821335, -1.2964655, 126.66067)
(-10.7, 10.626438, -20.733072, -1.136717, 124.21686000000001)
(-10.6, 11.308302000000001, -21.172464, -1.3825355, 122.33386000000002)
(-10.5, 10.429648, -20.596157, -0.64320195, 120.06943000000001)
(-10.4, 10.8849535, -20.661351999999997, -0.3901495, 118.01971)
(-10.3, 10.45083, -20.233, -0.7277571, 115.64625500000001)
(-10.2, 10.336596499999999, -20.050701, -0.30070248, 114.48178999999999)
(-10.1, 10.0118, -19.722372, -1.096486, 112.10818)
(-10.0, 10.113633, -19.30195, -0.085714914, 109.92688999999999)
(-9.9, 10.632909, -19.79375, -0.21923766, 107.886925)
(-9.8, 9.997225, -19.76049, 0.051941033, 106.10066)
(-9.7, 10.102144000000001, -18.892231, 0.16558519, 104.404465)
(-9.6, 9.994061, -19.079275, -0.014840198, 102.513695)
(-9.5, 9.9856, -19.227062, 0.1432455, 99.93771)
(-9.4, 9.797175, -19.294956, 0.25828840000000003, 98.05526)
(-9.3, 9.756836999999999, -18.367659, -0.15226789999999998, 96.0087)
(-9.2, 9.149104, -18.468264, 0.07860055, 94.75025)
(-9.1, 9.575704, -18.254517, 0.44018123, 92.99989000000001)
(-9.0, 9.609102, -18.157917, 0.2764047, 91.0986)
(-8.9, 8.7487755, -17.816803, 0.7876276999999999, 89.225235)
(-8.8, 8.811535000000001, -17.4471, 0.2957882, 87.30906)
(-8.7, 8.490911, -17.572067, 1.0391959000000002, 85.82028000000001)
(-8.6, 8.907814, -17.727707000000002, 1.0483444, 83.74932)
(-8.5, 8.693342, -17.651424, 0.6804177, 81.97771)
(-8.4, 8.192848, -17.093517000000002, 0.41850778, 80.42605999999999)
(-8.3, 8.443874000000001, -16.73235, 1.2244754999999998, 78.95714)
(-8.2, 8.869007, -16.443092, 1.1734028, 77.0556)
(-8.1, 8.582312, -17.049547, 1.2393827, 76.04297)
(-8.0, 8.454564, -16.62402, 0.596908, 74.39223)
(-7.9, 8.192283, -16.348554999999998, 0.7821627, 72.38314)
(-7.8, 8.309403999999999, -16.3033, 0.9133380999999999, 71.24091)
(-7.7, 7.9105062, -15.895184, 0.8397341, 68.90459399999999)
(-7.6, 7.6680655, -15.414816, 0.8619061, 67.862915)
(-7.5, 7.849951299999999, -15.963951999999999, 0.7936696, 66.38123)
(-7.4, 7.454269, -15.698563, 1.2440239, 64.50648000000001)
(-7.3, 8.096033, -14.801492000000001, 0.9463649, 62.8911)
(-7.2, 7.2346716, -14.774216000000001, 0.35111442, 62.201859999999996)
(-7.1, 7.442476299999999, -15.057058999999999, 0.7500066, 60.58969499999999)
(-7.0, 6.949319, -14.013279999999998, 0.45549616, 58.982209999999995)
(-6.9, 6.8056617, -14.202504000000001, 1.001949, 57.396595)
(-6.8, 7.277388, -14.319852, 0.8308718, 56.493233)
(-6.7, 7.1082234, -13.924456, 0.2115322, 54.884209999999996)
(-6.6, 6.850033, -13.33544, 0.45463535, 53.27775)
(-6.5, 7.150232000000001, -12.987835, -0.17628418, 52.44158)
(-6.4, 7.0554204, -12.828498, 0.46539176, 50.962821999999996)
(-6.3, 6.268019000000001, -12.738864, -0.07170418, 50.075706)
(-6.2, 6.7529573, -12.452337, -0.41906634, 48.932713)
(-6.1, 6.53737, -12.370272, -0.011464782, 47.47446)
(-6.0, 6.0445294, -12.307545, -0.6465253000000001, 46.105457)
(-5.9, 6.307569, -11.2650175, -0.2502793, 44.608433000000005)
(-5.8, 6.092744000000001, -10.996308, -0.30792909999999996, 44.0576)
(-5.7, 5.864985, -10.874376, -0.147337, 42.667393)
(-5.6, 6.1740184000000005, -11.234368, -0.56441814, 41.379673)
(-5.5, 5.4489527, -10.423198, -1.1322628000000001, 40.496235)
(-5.4, 6.1065955, -10.735776, -0.8521499, 39.152176000000004)
(-5.3, 6.2040057, -10.094047, -0.62457573, 37.675034000000004)
(-5.2, 5.742197, -9.569861, -1.2562621, 36.980434)
(-5.1, 5.1052723, -9.600067, -0.4685022, 36.061446999999994)
(-5.0, 5.961922599999999, -10.014899, -0.5538008000000001, 34.992477)
(-4.9, 5.393326999999999, -8.900081, -1.1044581, 33.83535)
(-4.8, 4.999235, -9.370882, -0.7158711999999999, 33.307575)
(-4.7, 5.621121, -8.923073, -0.83573824, 32.540896999999994)
(-4.6, 4.6354136, -8.991488, -0.7107156, 31.414062)
(-4.5, 5.4899435, -8.071876, -1.4734571, 30.497576000000002)
(-4.4, 4.5712532999999995, -7.8350253, -0.8717011999999998, 29.019257)
(-4.3, 5.043298, -8.400689, -1.3645024, 28.695969)
(-4.2, 4.722965, -7.8446746, -0.67564, 27.973461)
(-4.1, 4.406075, -7.435803999999999, -0.6638894000000001, 27.09042)
(-4.0, 4.1149572999999995, -7.742382000000001, -0.34156066, 26.057709)
(-3.9, 4.6815169999999995, -7.4908660000000005, -0.31624427, 25.658276)
(-3.8, 4.3475410000000005, -7.74022, -0.52646613, 24.548060999999997)
(-3.7, 3.9406035000000004, -7.325790400000001, -0.20176022, 23.478895)
(-3.6, 4.581373, -6.8560276, -0.40673268, 22.94657)
(-3.5, 3.7838426, -7.1503369999999995, 0.1446448, 21.793960000000002)
(-3.4, 3.5889933, -6.7491517000000005, -0.23998226, 21.815784)
(-3.3, 4.2094517, -6.640791, -0.053200595, 21.340935)
(-3.2, 3.9162698, -6.648745, 0.4062405, 20.365842999999998)
(-3.1, 4.0462110000000004, -6.1549926, 0.34621447, 19.502678)
(-3.0, 3.648476, -5.6523976, -0.22572342, 19.411054999999998)
(-2.9, 3.2752087000000003, -5.868144, -0.12125567, 18.590670000000003)
(-2.8, 4.0102763, -5.877377, 0.050558183, 17.6819)
(-2.7, 3.4163949999999996, -5.5671306, 0.13147312, 17.235159)
(-2.6, 3.241523, -5.198039, 0.94842845, 16.898169)
(-2.5, 3.2260833, -5.7955403, 0.18938036, 15.811257000000001)
(-2.4, 3.6987862999999996, -4.6503716, 0.8625896000000001, 15.747529)
(-2.3, 3.6523470000000002, -5.402725, 0.7513926999999999, 15.087222)
(-2.2, 3.1849317999999998, -5.172047599999999, 0.8717589, 14.844804000000002)
(-2.1, 2.8226717, -4.861232, 0.83210856, 14.232489000000001)
(-2.0, 2.9678035, -4.7544765, 0.8342261000000001, 14.29623)
(-1.9, 2.8954964, -4.118459, 1.2166183000000002, 13.326205999999999)
(-1.8, 3.2667553, -3.6447983, 1.4637437, 13.065006)
(-1.7, 2.749464, -4.0285587, 1.483644, 12.839578999999999)
(-1.6, 2.7475970000000003, -3.714068, 0.9481903, 12.37534)
(-1.5, 2.2453573, -3.8376775000000003, 1.3159133, 11.790266)
(-1.4, 2.4143677, -3.5897089999999996, 1.2187723, 12.332363)
(-1.3, 2.594773, -3.5747616, 1.1627372999999999, 12.148589)
(-1.2, 2.4590836, -2.5570487999999996, 1.3051353, 10.941583)
(-1.1, 2.6400878, -2.7902207000000003, 0.4582529, 10.896455)
(-1.0, 2.8070672, -2.2721276, 0.6995409, 11.420032)
(-0.9, 2.8354098999999997, -2.1050987, 1.1623685, 10.977433)
(-0.8, 2.611497, -2.3072875, 1.1416081, 10.892242)
(-0.7, 2.642666, -1.3178401000000002, 0.8203030000000001, 10.385823)
(-0.6, 2.4801848, -1.9261751, 0.30696952, 10.586652)
(-0.5, 1.8825631999999999, -1.4833988999999999, 0.47629252, 9.805024000000001)
(-0.4, 2.0509076, -0.5871089, 0.6624264, 10.40062)
(-0.3, 2.2667134, -1.0766847, 0.28521073, 10.497341)
(-0.2, 2.2886236, -0.40539563, 0.31358838, 9.589447)
(-0.1, 1.9209821, -0.29105362, 0.56959784, 9.806554)
(2.8421709999999997e-13, 1.9067929, -0.0018195593, -0.20943758, 10.454892)
(0.1, 2.5675627999999997, 0.21314143, -0.07627746, 9.632925)
(0.2, 2.6203866000000002, 0.43233487, 0.23280035, 9.700928)
(0.3, 2.685984, 0.42870235, -0.0051801326, 9.950183)
(0.4, 2.556809, 0.9721107, -0.48958027, 10.064566000000001)
(0.5, 2.1857252000000003, 1.5168687, -0.8207455, 10.63315)
(0.6, 2.5973191000000004, 1.2837363000000002, -0.9466986, 10.814232)
(0.7, 2.6568224, 1.9213405, -0.42546174, 10.640744999999999)
(0.8, 2.5259166, 1.5299996, -0.87506366, 10.281982000000001)
(0.9, 2.355599, 1.7754328000000001, -0.38038245, 11.144681)
(1.0, 2.5227093999999997, 2.6068822999999997, -1.1895535, 11.057227000000001)
(1.1, 2.4368656000000004, 3.090778, -0.56075966, 11.046545)
(1.2, 2.5026952999999996, 3.0585637, -0.950049, 11.300218)
(1.3, 2.881026, 3.4070795, -0.54310924, 11.878855999999999)
(1.4, 2.9710875, 2.8862727, -1.1532989, 11.924961)
(1.5, 3.08426, 3.8640508999999996, -0.8477469000000001, 12.674560000000001)
(1.6, 3.1883252, 3.5454738, -0.82777685, 12.3695135)
(1.7, 2.7833523999999996, 3.9687769999999998, -1.2616726, 13.263072)
(1.8, 3.1999372999999998, 4.498288, -0.58587694, 13.188809)
(1.9, 2.7145414, 4.473209400000001, -1.4232242, 14.097413000000001)
(2.0, 3.1100482999999994, 4.433781, -1.3168879999999998, 13.804634)
(2.1, 3.1710453, 5.1022453, -1.0430298, 14.5188055)
(2.2, 2.7229638, 4.5706367, -0.5396006, 14.772181)
(2.3, 3.4730835, 4.5359898, -1.1635925, 15.681099)
(2.4, 3.5808065000000004, 5.1122723, -0.99981534, 15.557141)
(2.5, 3.4515192999999997, 5.0335975, -0.55561495, 16.119871)
(2.6, 3.7003632000000004, 5.7465825, -0.036143563999999996, 16.482466)
(2.7, 3.2684278, 6.080696, -0.51586515, 16.993834)
(2.8, 4.001232, 6.1083074, -0.55949676, 17.854837)
(2.9, 4.025587600000001, 6.304126, -0.4960893, 18.356668)
(3.0, 3.700993, 6.07907, 0.129393, 19.430454)
(3.1, 3.7088089999999996, 6.109904, -0.34839413, 19.93463)
(3.2, 3.4699926, 5.9984093000000005, 0.11921127, 19.825029999999998)
(3.3, 4.3305583, 6.786357000000001, 0.37705323, 20.695332)
(3.4, 3.7323663000000002, 6.854392999999999, -0.1351826, 21.826984)
(3.5, 3.9668567, 6.5625729999999995, 0.48135254, 22.691542000000002)
(3.6, 4.6750193, 7.2932177, 0.7382953, 23.407677)
(3.7, 4.1175323, 7.379510400000001, 0.06591794, 23.758926000000002)
(3.8, 4.2340584, 6.860232400000001, 0.9617181, 24.189684)
(3.9, 4.4459352, 7.3089647, 1.0266176, 25.194616)
(4.0, 4.463535, 7.3510919999999995, 1.0142055, 25.68515)
(4.1, 5.032319, 8.18368, 0.9927039000000001, 26.422174)
(4.2, 4.288235, 7.5989685, 1.0891473999999999, 28.110492999999998)
(4.3, 4.398274, 8.362309, 0.4941162, 28.800790000000003)
(4.4, 4.632341, 8.752326, 1.342638, 29.806459999999998)
(4.5, 4.6114845, 8.842217999999999, 1.3531665000000002, 30.638071000000004)
(4.6, 5.063789, 8.406047000000001, 0.64418656, 31.432703000000004)
(4.7, 5.4624352, 8.420763, 0.70212764, 32.565723)
(4.8, 5.6185317, 8.79778, 1.1547709, 32.696262)
(4.9, 5.0919175, 9.244471, 0.95698154, 34.074562)
(5.0, 5.1049514, 9.076412, 0.5227636999999999, 35.09539)
(5.1, 5.45758, 9.513353, 0.81884074, 36.355647999999995)
(5.2, 5.4457574, 10.450724000000001, 1.129615, 37.10103)
(5.3, 5.709005400000001, 10.422239, 1.1554403999999998, 38.50662)
(5.4, 6.251469, 10.46177, 0.9204110000000001, 39.302425)
(5.5, 6.104926, 10.283619999999999, 0.8724166999999999, 40.577785)
(5.6, 6.245378, 10.556853, 0.46228322, 41.373833000000005)
(5.7, 5.9275246, 11.333424, 0.716355, 42.020565000000005)
(5.8, 6.377687, 11.198328, 0.6598564, 43.69142)
(5.9, 6.4171510000000005, 11.244988000000001, -0.019758081, 44.828278000000005)
(6.0, 6.2716055, 12.090538, 0.04401142, 45.636109999999995)
(6.1, 6.662482700000001, 12.460741, -0.15073007, 47.39976)
(6.2, 6.9237266, 12.018989, 0.42065212, 48.699913)
(6.3, 6.4646153, 12.121255999999999, 0.16416429999999999, 50.008575)
(6.4, 6.6074324, 13.037908, 0.31232992, 51.200695)
(6.5, 7.2870946, 13.140023999999999, -0.52095586, 52.280334)
(6.6, 7.3306704, 13.068602, -0.6549376, 53.60403)
(6.7, 6.847502, 13.551454999999999, -0.41368085, 55.04289)
(6.8, 7.459199400000001, 14.024370000000001, -0.3752847, 56.41539399999999)
(6.9, 7.744263, 14.498898, -0.11450659, 57.151385999999995)
(7.0, 7.5429673, 14.624948999999999, -0.92380804, 58.598434)
(7.1, 7.285284, 15.026645000000002, -1.1042324, 60.309025)
(7.2, 7.293435000000001, 15.188842999999999, -0.6065066, 62.265274)
(7.3, 7.881856, 14.838598999999999, -0.89105904, 63.191055000000006)
(7.4, 7.384869, 14.983051000000001, -0.44359496, 64.653984)
(7.5, 7.892156, 15.279047, -1.3210838, 65.876785)
(7.6, 8.295798, 15.245973999999999, -0.9639416999999999, 67.96185)
(7.7, 7.5499015, 15.401112, -1.0715193, 69.36669)
(7.8, 8.496568, 16.349257, -1.4645541000000002, 71.33346999999999)
(7.9, 8.514796, 16.31658, -1.0269487, 72.79301)
(8.0, 8.50117, 16.851439000000003, -1.0996363, 74.0216)
(8.1, 8.735185000000001, 16.299988, -1.0440655, 76.079704)
(8.2, 8.304382, 17.1317, -1.4200826000000002, 76.89071)
(8.3, 8.277512, 17.434929999999998, -1.3328252, 79.132835)
(8.4, 8.386362, 16.98571, -1.0694915, 80.29113000000001)
(8.5, 8.483796, 17.370565, -1.2503654, 82.11903000000001)
(8.6, 8.64038, 17.792437, -1.1695739, 84.24904000000001)
(8.7, 9.364765, 18.041132, -0.44884038, 86.13578000000001)
(8.8, 9.085411, 18.196892000000002, -0.84043986, 87.68579)
(8.9, 9.539479, 17.559044, -0.84983546, 89.11908000000001)
(9.0, 9.355122, 17.829462, -0.72017187, 90.646225)
(9.1, 9.649523, 18.253935000000002, -0.07314411, 92.75645)
(9.2, 9.097502, 18.741976, 0.16533749, 94.38358000000001)
(9.3, 9.988317, 19.14486, 0.018753966, 96.56858000000001)
(9.4, 9.268267, 18.554935, -0.3581066, 98.28399999999999)
(9.5, 9.733953999999999, 18.587108999999998, 0.56480235, 99.901535)
(9.6, 9.724414, 19.381361, -0.23181910000000003, 102.59569499999999)
(9.7, 9.788444, 18.854295999999998, 0.34212863, 103.72068)
(9.8, 10.038673, 19.350428, 0.77611804, 105.965195)
(9.9, 10.200377, 19.905037, 0.53346294, 108.053894)
(10.0, 10.257575, 19.603545999999998, 1.0251127, 109.979996)
(10.1, 10.112908000000001, 20.194376000000002, 0.6610545, 111.7005)
(10.2, 9.970628, 20.515282, 0.5173698, 114.35175)
(10.3, 10.819791, 20.304657000000002, 1.0647636999999999, 115.82179)
(10.4, 11.018786, 20.752426, 0.6615916000000001, 117.92371999999999)
(10.5, 10.541011, 20.523415, 0.47194043, 120.6493)
(10.6, 11.230107, 20.925589000000002, 1.2618916999999998, 122.3669)
(10.7, 11.400413499999999, 21.139492, 0.79212743, 124.49401)
(10.8, 11.397608, 21.54235, 0.8970019, 126.619965)
(10.9, 10.674099, 20.889001999999998, 1.4205146999999998, 128.89688)
(11.0, 11.186346, 21.089315, 1.4174771000000002, 130.63113)
(11.1, 11.190142, 21.330460000000002, 1.4224523, 133.65329)
(11.2, 11.48581, 21.559114, 0.82620627, 134.98712)
(11.3, 11.049973, 21.794386, 0.76976115, 137.87778)
(11.4, 11.571982, 22.383318, 0.75888294, 140.06294)
(11.5, 11.424038000000001, 22.602709, 0.65970004, 142.24652)
(11.6, 12.023057000000001, 22.949884, 0.86875653, 144.87683)
(11.7, 11.875231, 23.261421, 1.1899718000000001, 146.82835)
(11.8, 11.541917, 23.460941000000002, 0.78738993, 149.09949)
(11.9, 11.9601345, 23.859987, 0.7359703000000001, 151.59409)
(12.0, 12.121654, 23.513693, 0.42470187, 153.95657)
(12.1, 12.161585, 23.55516, 0.19664906, 156.41214)
(12.2, 12.715347999999999, 23.798344, 0.5431225000000001, 158.52011000000002)
(12.3, 12.64989, 24.380083, 0.2340303, 160.97881999999998)
(12.4, 12.299296, 25.193338, 0.60675424, 163.87411)
(12.5, 12.372492, 25.011817999999998, 0.36461407, 166.37994)
(12.6, 12.351158999999999, 24.856575, -0.38231578, 168.73498999999998)
(12.7, 12.407368, 25.943338, 0.34920213, 171.74316000000002)

In [7]:
ideal = pd.read_csv('ideal.csv', index_col = 0)
ideal.head()

,y1,y2,y3,y4,y5,y6,y7,y8,y9,y10,...,y41,y42,y43,y44,y45,y46,y47,y48,y49,y50
x,,,,,,,,,,,,,,,,,,,,,
-20.0,-0.912945,0.408082,9.087055,5.408082,-9.087055,0.912945,-0.839071,-0.850919,0.816164,18.258905,...,-40.456474,40.204040,2.995732,-0.008333,12.995732,5.298317,-5.298317,-0.186278,0.912945,0.396850
-19.9,-0.867644,0.497186,9.132356,5.497186,-9.132356,0.867644,-0.865213,0.168518,0.994372,17.266117,...,-40.233820,40.048590,2.990720,-0.008340,12.990720,5.293305,-5.293305,-0.215690,0.867644,0.476954
-19.8,-0.813674,0.581322,9.186326,5.581322,-9.186326,0.813674,-0.889191,0.612391,1.162644,16.110740,...,-40.006836,39.890660,2.985682,-0.008347,12.985682,5.288267,-5.288267,-0.236503,0.813674,0.549129
-19.7,-0.751573,0.659649,9.248426,5.659649,-9.248426,0.751573,-0.910947,-0.994669,1.319299,14.805996,...,-39.775787,39.729824,2.980619,-0.008354,12.980619,5.283204,-5.283204,-0.247887,0.751573,0.612840
-19.6,-0.681964,0.731386,9.318036,5.731386,-9.318036,0.681964,-0.930426,0.774356,1.462772,13.366487,...,-39.540980,39.565693,2.975530,-0.008361,12.975530,5.278115,-5.278115,-0.249389,0.681964,0.667902

In [8]:
ideal.tail(10)

,y1,y2,y3,y4,y5,y6,y7,y8,y9,y10,...,y41,y42,y43,y44,y45,y46,y47,y48,y49,y50
x,,,,,,,,,,,,,,,,,,,,,
19.0,0.149877,0.988705,10.149878,5.988705,-10.149878,-0.149877,-0.997172,0.279387,1.977409,2.847667,...,38.074940,-37.505650,2.944439,-0.012346,12.944439,5.247024,-5.247024,0.074092,0.149877,0.835315
19.1,0.247834,0.968802,10.247834,5.968802,-10.247834,-0.247834,-0.992170,0.375793,1.937605,4.733633,...,38.323917,-37.715600,2.949688,-0.012361,12.949688,5.252274,-5.252274,0.120051,0.247834,0.824208
19.2,0.343315,0.939220,10.343315,5.939220,-10.343315,-0.343315,-0.984688,-0.878952,1.878441,6.591647,...,38.571660,-37.930390,2.954910,-0.012376,12.954910,5.257495,-5.257495,0.161224,0.343315,0.807098
19.3,0.435365,0.900254,10.435366,5.900254,-10.435366,-0.435365,-0.974745,0.977765,1.800508,8.402552,...,38.817684,-38.149870,2.960105,-0.012392,12.960105,5.262690,-5.262690,0.195970,0.435365,0.783485
19.4,0.523066,0.852292,10.523066,5.852292,-10.523066,-0.523066,-0.962365,-0.590048,1.704585,10.147476,...,39.061530,-38.373856,2.965273,-0.012407,12.965273,5.267858,-5.267858,0.222902,0.523066,0.752791
19.5,0.605540,0.795815,10.605540,5.795815,-10.605540,-0.605540,-0.947580,-0.117020,1.591630,11.808027,...,39.302770,-38.602093,2.970414,-0.012422,12.970414,5.273000,-5.273000,0.240949,0.605540,0.714434
19.6,0.681964,0.731386,10.681964,5.731386,-10.681964,-0.681964,-0.930426,0.774356,1.462772,13.366487,...,39.540980,-38.834310,2.975530,-0.012438,12.975530,5.278115,-5.278115,0.249389,0.681964,0.667902
19.7,0.751573,0.659649,10.751574,5.659649,-10.751574,-0.751573,-0.910947,-0.994669,1.319299,14.805996,...,39.775787,-39.070175,2.980619,-0.012453,12.980619,5.283204,-5.283204,0.247887,0.751573,0.612840
19.8,0.813674,0.581322,10.813674,5.581322,-10.813674,-0.813674,-0.889191,0.612391,1.162644,16.110740,...,40.006836,-39.309338,2.985682,-0.012469,12.985682,5.288267,-5.288267,0.236503,0.813674,0.549129
19.9,0.867644,0.497186,10.867644,5.497186,-10.867644,-0.867644,-0.865213,0.168518,0.994372,17.266117,...,40.233820,-39.551407,2.990720,-0.012484,12.990720,5.293305,-5.293305,0.215690,0.867644,0.476954

In [9]:
dbname = 'ideal.db'

conn = sqlite3.connect(dbname)
cur = conn.cursor()

In [10]:
ideal.to_sql('sample', conn, if_exists = 'replace')

select_sql = 'SELECT * FROM sample'
for row in cur.execute(select_sql):
    print(row)

cur.close()
conn.close()

(-20.0, -0.9129453000000002, 0.40808207, 9.087055, 5.408082, -9.087055, 0.9129453000000002, -0.8390715, -0.85091937, 0.81616414, 18.258905, -20.0, -58.0, -45.0, 20.0, 13.0, 400.0, -400.0, 800.0, 410.0, 289.0, -8000.0, 8000.0, 8000.0, -16000.0, -23995.0, -5832.0, 10648.0, -8020.0, -7600.0, -8795.0, 20.0, 4.472136, 20.12461, -0.7464143, 10.0, 100.0, -20.0, -1.3210273000000001, 399.08707000000004, 899.5919, -40.456474, 40.20404, 2.9957323, -0.008333334, 12.995732, 5.298317400000001, -5.298317400000001, -0.18627828, 0.9129453000000002, 0.39684959999999997)
(-19.9, -0.8676440999999999, 0.4971858, 9.132356, 5.4971857, -9.132356, 0.8676440999999999, -0.8652126, 0.16851768, 0.9943716, 17.266117, -19.9, -57.7, -44.8, 19.9, 12.95, 396.01, -396.01, 792.02, 406.01, 285.61, -7880.599, 7880.599, 7880.599, -15761.198, -23636.797000000002, -5735.339, 10503.458999999999, -7900.499, -7484.589, -8667.619, 19.9, 4.460942, 20.025234, -0.6204504, 9.9, 99.5, -19.9, -1.3648299, 395.14236, 893.5128, -40.23382, 40.048590000000004, 2.9907197999999995, -0.008340283, 12.99072, 5.293305, -5.293305, -0.21569017, 0.8676440999999999, 0.47695395)
(-19.8, -0.81367373, 0.58132184, 9.186326, 5.5813217, -9.186326, 0.81367373, -0.88919115, 0.6123911, 1.1626437, 16.11074, -19.8, -57.4, -44.6, 19.8, 12.9, 392.04, -392.04, 784.08, 402.04, 282.24, -7762.392, 7762.392, 7762.392, -15524.784, -23282.176, -5639.7519999999995, 10360.232, -7782.191999999999, -7370.352, -8541.472, 19.8, 4.449719, 19.925863, -0.47573867, 9.8, 99.0, -19.8, -1.3949956000000001, 391.22632000000004, 887.4587, -40.006836, 39.89066, 2.985682, -0.008347246, 12.985682, 5.288266999999999, -5.288266999999999, -0.23650314, 0.81367373, 0.5491291)
(-19.7, -0.75157344, 0.65964943, 9.248426, 5.6596494, -9.248426, 0.75157344, -0.91094714, -0.99466854, 1.3192989, 14.805995999999999, -19.7, -57.1, -44.4, 19.7, 12.85, 388.09, -388.09, 776.18, 398.09, 278.89, -7645.3730000000005, 7645.3730000000005, 7645.3730000000005, -15290.746000000001, -22931.12, -5545.233, 10218.313, -7665.073, -7257.283, -8416.553, 19.7, 4.438468, 19.826498, -0.31643602, 9.7, 98.5, -19.7, -1.4112228, 387.33844, 881.43036, -39.775787, 39.729824, 2.9806187, -0.008354219, 12.9806185, 5.283203599999999, -5.283203599999999, -0.24788749, 0.75157344, 0.6128399)
(-19.6, -0.6819636, 0.7313861, 9.318036, 5.731386, -9.318036, 0.6819636, -0.9304263, 0.7743557, 1.4627723, 13.366487, -19.6, -56.8, -44.2, 19.6, 12.8, 384.16, -384.16, 768.32, 394.16, 275.56, -7529.536, 7529.536, 7529.536, -15059.072, -22583.607000000004, -5451.776, 10077.696, -7549.1359999999995, -7145.376, -8292.856, 19.6, 4.427189, 19.727139, -0.147038, 9.6, 98.0, -19.6, -1.4133497, 383.47803, 875.4286, -39.54098, 39.565692999999996, 2.9755297, -0.008361204, 12.975530000000001, 5.278115000000001, -5.278115000000001, -0.24938935, 0.6819636, 0.6679019)
(-19.5, -0.60553986, 0.7958149999999999, 9.39446, 5.795815, -9.39446, 0.60553986, -0.9475798000000001, -0.11702018, 1.5916299999999999, 11.808027000000001, -19.5, -56.5, -44.0, 19.5, 12.75, 380.25, -380.25, 760.5, 390.25, 272.25, -7414.875, 7414.875, 7414.875, -14829.75, -22239.625, -5359.375, 9938.375, -7434.375, -7034.625, -8170.375, 19.5, 4.4158800000000005, 19.627786999999998, 0.027781596000000002, 9.5, 97.5, -19.5, -1.4013548, 379.64447, 869.45416, -39.30277, 39.397907000000004, 2.9704144, -0.008368201, 12.970414, 5.273, -5.273, -0.24094884, 0.60553986, 0.7144341)
(-19.4, -0.52306575, 0.8522923000000001, 9.476934, 5.8522925, -9.476934, 0.52306575, -0.96236485, -0.59004813, 1.7045846000000002, 10.147476, -19.4, -56.2, -43.8, 19.4, 12.7, 376.36, -376.36, 752.72, 386.36, 268.96, -7301.384, 7301.384, 7301.384, -14602.768, -21899.152000000002, -5268.024, 9800.344000000001, -7320.784000000001, -6925.024, -8049.104, 19.4, 4.404543, 19.52844, 0.20333645, 9.4, 97.0, -19.4, -1.3753581, 375.83693999999997, 863.5077, -39.06153, 39.226147, 2.9652731, -0.00837521, 12.965273, 5.267858, -5.267858, -0.22290246, 0.52306575, 0.75279135)
(-19.3, -0.43536535, 0.90025383, 9.564634, 5.900254, -9.564634, 0.43536535, -0.97474456, 0.97776526, 1.8005077, 8.402552, -19.3, -55.9, -43.6, 19.3, 12.65, 372.49, -372.49, 744.98, 382.49, 265.69, -7189.057, 7189.057, 7189.057, -14378.114, -21562.172000000002, -5177.717000000001, 9663.597, -7208.357, -6816.566999999999, -7929.036999999999, 19.3, 4.393176599999999, 19.429102, 0.37509164, 9.3, 96.5, -19.3, -1.3356192, 372.05463, 857.5897, -38.817684, 39.050125, 2.9601052000000005, -0.00838223, 12.960105, 5.26269, -5.26269, -0.19596967, 0.43536535, 0.7834846999999999)
(-19.2, -0.34331492, 0.93922037, 9.656685000000001, 5.939220400000001, -9.656685000000001, 0.34331492, -0.98468786, -0.87895167, 1.8784406999999999, 6.5916467, -19.2, -55.6, -43.4, 19.2, 12.6, 368.64, -368.64, 737.28, 378.64, 262.44, -7077.888000000001, 7077.888000000001, 7077.888000000001, -14155.776000000002, -21228.664, -5088.448, 9528.128, -7097.088000000001, -6709.2480000000005, -7810.168000000001, 19.2, 4.3817806, 19.32977, 0.5388199, 9.2, 96.0, -19.2, -1.2825353000000002, 368.2967, 851.7008, -38.571659999999994, 38.869609999999994, 2.9549103, -0.008389262, 12.95491, 5.257495400000001, -5.257495400000001, -0.16122419, 0.34331492, 0.80709803)
(-19.1, -0.2478342, 0.96880245, 9.752166, 5.9688025, -9.752166, 0.2478342, -0.9921700000000001, 0.37579286, 1.9376049, 4.7336335, -19.1, -55.3, -43.2, 19.1, 12.55, 364.81, -364.81, 729.62, 374.81, 259.21, -6967.871, 6967.871, 6967.871, -13935.742, -20898.613, -5000.210999999999, 9393.931, -6986.971, -6603.061, -7692.491, 19.1, 4.3703547, 19.230444, 0.6907439999999999, 9.1, 95.5, -19.1, -1.2166367, 364.56216, 845.8412, -38.323917, 38.684402, 2.9496884, -0.008396306, 12.949688, 5.2522736, -5.2522736, -0.1200512, 0.2478342, 0.82420814)
(-19.0, -0.14987720000000002, 0.9887046, 9.850122, 5.9887046999999995, -9.850122, 0.14987720000000002, -0.9971722, 0.27938655, 1.9774092, 2.847667, -19.0, -55.0, -43.0, 19.0, 12.5, 361.0, -361.0, 722.0, 371.0, 256.0, -6859.0, 6859.0, 6859.0, -13718.0, -20572.0, -4913.0, 9261.0, -6878.0, -6498.0, -7576.0, 19.0, 4.358899, 19.131126000000002, 0.8276595999999999, 9.0, 95.0, -19.0, -1.1385819, 360.85013, 840.0113, -38.074940000000005, 38.49435, 2.944439, -0.008403362, 12.944439, 5.247024, -5.247024, -0.07409214, 0.14987720000000002, 0.8353145000000001)
(-18.9, -0.050422687, 0.9987280000000001, 9.949577, 5.998728, -9.949577, 0.050422687, -0.99968195, -0.80255306, 1.9974560000000001, 0.9529888000000001, -18.9, -54.7, -42.8, 18.9, 12.45, 357.21, -357.21, 714.42, 367.21, 252.81, -6751.269, 6751.269, 6751.269, -13502.538, -20248.807, -4826.809, 9129.329, -6770.169, -6394.059, -7460.689, 18.9, 4.3474129999999995, 19.031814999999998, 0.94703484, 8.9, 94.5, -18.9, -1.0491507, 357.15958, 834.2112400000001, -37.82521, 38.299362, 2.939162, -0.008410429, 12.939162, 5.241747, -5.241747, -0.025179273999999998, 0.050422687, 0.840783)
(-18.8, 0.04953564, 0.9987724, 10.049536, 5.998772, -10.049536, -0.04953564, -0.99969304, 0.9999414000000001, 1.9975448, -0.93127006, -18.8, -54.4, -42.6, 18.8, 12.4, 353.44, -353.44, 706.88, 363.44, 249.64, -6644.672, 6644.672, 6644.672, -13289.344, -19929.016, -4741.6320000000005, 8998.912, -6663.472, -6291.232, -7346.552, 18.8, 4.3358965, 18.932512, 1.0470818000000002, 8.8, 94.0, -18.8, -0.9492367, 353.48953, 828.4412, -37.575233000000004, 38.099384, 2.933857, -0.008417509, 12.933857000000001, 5.236442, -5.236442, 0.024737414, -0.04953564, 0.8408071)
(-18.7, 0.14899902, 0.98883736, 10.148999, 5.9888372, -10.148999, -0.14899902, -0.99720544, -0.82669914, 1.9776747, -2.7862818, -18.7, -54.1, -42.4, 18.7, 12.35, 349.69, -349.69, 699.38, 359.69, 246.49, -6539.203, 6539.203, 6539.203, -13078.406, -19612.61, -4657.463, 8869.743, -6557.903, -6189.513000000001, -7233.5830000000005, 18.7, 4.32435, 18.833216, 1.1267983, 8.7, 93.5, -18.7, -0.8398382999999999, 349.839, 822.7012, -37.3255, 37.894417, 2.9285235000000003, -0.0084246, 12.928523, 5.2311087, -5.2311087, 0.0736679, -0.14899902, 0.83538747)
(-18.6, 0.24697366, 0.9690222, 10.246974, 5.9690223, -10.246974, -0.24697366, -0.99222535, 0.37538130000000003, 1.9380444, -4.59371, -18.6, -53.8, -42.2, 18.6, 12.3, 345.96, -345.96, 691.92, 355.96, 243.36, -6434.856, 6434.856, 6434.856, -12869.712, -19299.568, -4574.295999999999, 8741.815999999999, -6453.456, -6088.896, -7121.776, 18.6, 4.312772, 18.733926999999998, 1.1859777, 8.6, 93.0, -18.6, -0.7220485, 346.20697, 816.9909700000001, -37.07651, 37.684509999999996, 2.9231615, -0.008431703, 12.9231615, 5.225746599999999, -5.225746599999999, 0.11966148, -0.24697366, 0.8243325999999999)
(-18.5, 0.34248063, 0.9395249, 10.342481, 5.939525, -10.342481, -0.34248063, -0.9847652, 0.1825695, 1.8790498, -6.335891200000001, -18.5, -53.5, -42.0, 18.5, 12.25, 342.25, -342.25, 684.5, 352.25, 240.25, -6331.625, 6331.625, 6331.625, -12663.25, -18989.875, -4492.125, 8615.125, -6350.125, -5989.375, -7011.125, 18.5, 4.3011627, 18.634645000000003, 1.2251877, 8.5, 92.5, -18.5, -0.5970443, 342.59247, 811.3105, -36.828759999999996, 37.46976, 2.9177706000000003, -0.008438818, 12.917769999999999, 5.220356, -5.220356, 0.16088453, -0.34248063, 0.8072778)
(-18.4, 0.43456563, 0.9006402, 10.434566, 5.90064, -10.434566, -0.43456563, -0.9748435999999999, -0.6683636, 1.8012804, -7.996007400000001, -18.4, -53.2, -41.8, 18.4, 12.2, 338.56, -338.56, 677.12, 348.56, 237.16, -6229.504, 6229.504, 6229.504, -12459.008, -18683.512, -4410.944, 8489.664, -6247.904, -5890.944, -6901.624, 18.4, 4.289522, 18.535372, 1.2457184, 8.4, 92.0, -18.4, -0.46607456, 338.99457, 805.65936, -36.582718, 37.25032, 2.9123507, -0.008445946, 12.912351, 5.214936, -5.214936, 0.19569363, -0.43456563, 0.78372467)
(-18.3, 0.5223085999999999, 0.85275656, 10.522308, 5.8527565, -10.522308, -0.5223085999999999, -0.9624855, 0.95221686, 1.7055131000000001, -9.558247999999999, -18.3, -52.9, -41.6, 18.3, 12.15, 334.89, -334.89, 669.78, 344.89, 234.09, -6128.486999999999, 6128.486999999999, 6128.486999999999, -12256.973999999998, -18380.46, -4330.747, 8365.427, -6146.786999999999, -5793.597, -6793.267, 18.3, 4.27785, 18.436106, 1.2495023, 8.3, 91.5, -18.3, -0.33044797, 335.41232, 800.03723, -36.338844, 37.026379999999996, 2.9069011000000002, -0.008453085, 12.906901, 5.209486, -5.209486, 0.22270104, -0.5223085999999999, 0.7530968000000001)
(-18.2, 0.6048328000000001, 0.79635245, 10.604833, 5.796352400000001, -10.604833, -0.6048328000000001, -0.9477216, -0.98045707, 1.5927049, -11.007957000000001, -18.2, -52.6, -41.4, 18.2, 12.1, 331.24, -331.24, 662.48, 341.24, 231.04, -6028.568, 6028.568, 6028.568, -12057.136, -18080.703, -4251.528, 8242.408000000001, -6046.768, -5697.328, -6686.048000000001, 18.2, 4.2661457, 18.336847, 1.2390101, 8.2, 91.0, -18.2, -0.19151965, 331.84482, 794.4436599999999, -36.097584000000005, 36.798176, 2.9014215, -0.008460236999999999, 12.901422, 5.2040067, -5.2040067, 0.24083005, -0.6048328000000001, 0.7148101)
(-18.1, 0.68131375, 0.73199147, 10.6813135, 5.7319913, -10.6813135, -0.68131375, -0.9305889, 0.77351207, 1.4639829, -12.3317795, -18.1, -52.3, -41.2, 18.1, 12.05, 327.61, -327.61, 655.22, 337.61, 228.01, -5929.741, 5929.741, 5929.741, -11859.482, -17784.223, -4173.281, 8120.601, -5947.840999999999, -5602.130999999999, -6579.960999999999, 18.1, 4.2544093, 18.237598000000002, 1.2171253, 8.1, 90.5, -18.1, -0.05067773, 328.29132000000004, 788.878, -35.859344, 36.565994, 2.895912, -0.0084674, 12.895912, 5.198497, -5.198497, 0.24935794, -0.68131375, 0.6683523)
(-18.0, 0.75098723, 0.6603167, 10.750987, 5.660317, -10.750987, -0.75098723, -0.91113025, -0.40406522, 1.3206334, -13.517771, -18.0, -52.0, -41.0, 18.0, 12.0, 324.0, -324.0, 648.0, 334.0, 225.0, -5832.0, 5832.0, 5832.0, -11664.0, -17491.0, -4096.0, 8000.0, -5850.0, -5508.0, -6475.0, 18.0, 4.2426405, 18.138357, 1.1870053999999999, 8.0, 90.0, -18.0, 0.09067054, 324.75097999999997, 783.33966, -35.624508, 36.33016, 2.8903717999999996, -0.008474576, 12.890371, 5.192957, -5.192957, 0.24794471, -0.75098723, 0.613367)
(-17.9, 0.81315714, 0.58204424, 10.813157, 5.582044000000001, -10.813157, -0.81315714, -0.8893941999999999, -0.032444972999999995, 1.1640885, -14.555512, -17.9, -51.7, -40.8, 17.9, 11.95, 320.41, -320.41, 640.82, 330.41, 222.01, -5735.339, 5735.339, 5735.339, -11470.678, -17201.018, -4019.679, 7880.599, -5753.2390000000005, -5414.929, -6371.159000000001, 17.9, 4.2308392999999995, 18.039123999999997, 1.1519326, 7.9, 89.5, -17.9, 0.23111285, 321.22314, 777.82794, -35.39342, 36.091021999999995, 2.8848007, -0.008481764000000001, 12.884801, 5.187386, -5.187386, 0.23664671, -0.81315714, 0.54973274)
(-17.8, 0.86720216, 0.49795622, 10.867202, 5.497956299999999, -10.867202, -0.86720216, -0.8654351999999998, 0.44471678, 0.99591243, -15.436198999999998, -17.8, -51.4, -40.6, 17.8, 11.9, 316.84, -316.84, 633.68, 326.84, 219.04, -5639.7519999999995, 5639.7519999999995, 5639.7519999999995, -11279.503999999999, -16914.256, -3944.312, 7762.392, -5657.552, -5322.911999999999, -6268.432, 17.8, 4.2190046, 17.9399, 1.1151626000000001, 7.8, 89.0, -17.8, 0.36924598, 317.7072, 772.34204, -35.166396999999996, 35.84898, 2.8791986, -0.008488964, 12.879197999999999, 5.1817836999999995, -5.1817836999999995, 0.21591435, -0.86720216, 0.47763094)
(-17.7, 0.91258246, 0.40889275, 10.912582, 5.4088926, -10.912582, -0.91258246, -0.83931303, -0.76385504, 0.8177854999999999, -16.15271, -17.7, -51.1, -40.4, 17.7, 11.85, 313.29, -313.29, 626.58, 323.29, 216.09, -5545.233, 5545.233, 5545.233, -11090.466, -16630.7, -3869.893, 7645.3730000000005, -5562.933000000001, -5231.943, -6166.813, 17.7, 4.207136599999999, 17.840683, 1.0797757, 7.7, 88.5, -17.7, 0.5036897, 314.20257999999995, 766.8811, -34.943709999999996, 35.604446, 2.8735647, -0.008496176, 12.873565, 5.17615, -5.17615, 0.18657418, -0.91258246, 0.3975936)
(-17.6, 0.9488445, 0.31574374, 10.948845, 5.3157440000000005, -10.948845, -0.9488445, -0.81109303, 0.951376, 0.6314875, -16.699663, -17.6, -50.8, -40.2, 17.6, 11.8, 309.76, -309.76, 619.52, 319.76, 213.16, -5451.776, 5451.776, 5451.776, -10903.552, -16350.328000000001, -3796.4159999999997, 7529.536, -5469.376, -5142.016, -6066.295999999999, 17.6, 4.195235299999999, 17.741476000000002, 1.0485386, 7.6, 88.0, -17.6, 0.63310075, 310.70883, 761.4443, -34.72558, 35.357872, 2.867899, -0.008503402, 12.867899000000001, 5.170484, -5.170484, 0.14979586, -0.9488445, 0.31052354)
(-17.5, 0.975626, 0.21943997, 10.975626, 5.2194400000000005, -10.975626, -0.975626, -0.7808457, -0.9984723, 0.43887994, -17.073456, -17.5, -50.5, -40.0, 17.5, 11.75, 306.25, -306.25, 612.5, 316.25, 210.25, -5359.375, 5359.375, 5359.375, -10718.75, -16073.125, -3723.875, 7414.875, -5376.875, -5053.125, -5966.875, 17.5, 4.1833, 17.642279000000002, 1.0237799, 7.5, 87.5, -17.5, 0.75618607, 307.22562, 756.0306, -34.512188, 35.10972, 2.8622009999999998, -0.008510638000000001, 12.862200999999999, 5.164786, -5.164786, 0.107045665, -0.975626, 0.21768305)
(-17.4, 0.9926594000000001, 0.12094360000000001, 10.99266, 5.1209435, -10.99266, -0.9926594000000001, -0.7486465999999999, 0.91961735, 0.24188720000000002, -17.272274, -17.4, -50.2, -39.8, 17.4, 11.7, 302.76, -302.76, 605.52, 312.76, 207.36, -5268.024, 5268.024, 5268.024, -10536.048, -15799.072, -3652.264, 7301.384, -5285.424, -4965.264, -5868.544, 17.4, 4.1713309999999995, 17.543089000000002, 1.0072868000000001, 7.4, 87.0, -17.4, 0.8717158000000002, 303.75266, 750.63904, -34.303670000000004, 34.860473999999996, 2.8564700000000003, -0.008517887, 12.85647, 5.159055, -5.159055, 0.0600279, -0.9926594000000001, 0.120648965)
(-17.3, 0.99977446, 0.021238807999999998, 10.999774, 5.021239, -10.999774, -0.99977446, -0.71457636, -0.7437734, 0.042477615, -17.296097, -17.3, -49.9, -39.6, 17.3, 11.65, 299.29, -299.29, 598.58, 309.29, 204.49, -5177.717000000001, 5177.717000000001, 5177.717000000001, -10355.434000000001, -15528.151000000002, -3581.577, 7189.057, -5195.017, -4878.427, -5771.297, 17.3, 4.159326999999999, 17.44391, 1.0002255, 7.3, 86.5, -17.3, 0.97853565, 300.28976, 745.2687400000001, -34.100113, 34.610620000000004, 2.8507066, -0.008525149000000001, 12.850706, 5.1532917000000005, -5.1532917000000005, 0.010617008, -0.99977446, 0.021237211000000002)
(-17.2, 0.9969001000000001, -0.07867819999999999, 10.9969, 4.921322, -10.9969, -0.9969001000000001, -0.67872006, 0.50578403, -0.15735639999999998, -17.14668, -17.2, -49.6, -39.4, 17.2, 11.6, 295.84, -295.84, 591.68, 305.84, 201.64, -5088.448, 5088.448, 5088.448, -10176.896, -15260.344, -3511.808, 7077.888000000001, -5105.648, -4792.608, -5675.128000000001, 17.2, 4.1472883000000005, 17.344739999999998, 1.0030904, 7.2, 86.0, -17.2, 1.0755781999999998, 296.8369, 739.9187, -33.90155, 34.360659999999996, 2.8449093999999997, -0.0085324235, 12.84491, 5.1474943, -5.1474943, -0.039217148, -0.9969001000000001, -0.07859705)
(-17.1, 0.984065, -0.17780907, 10.984065, 4.8221907999999996, -10.984065, -0.984065, -0.6411673000000001, -0.23953144, -0.35561815, -16.82751, -17.1, -49.3, -39.2, 17.1, 11.55, 292.41, -292.41, 584.82, 302.41, 198.81, -5000.210999999999, 5000.210999999999, 5000.210999999999, -10000.421999999999, -14995.633, -3442.9509999999996, 6967.871, -5017.311, -4707.8009999999995, -5580.031, 17.1, 4.1352150000000005, 17.245579, 1.015681, 7.1, 85.5, -17.1, 1.161874, 293.39407, 734.5878, -33.707966, 34.111095, 2.8390784, -0.008539709, 12.839079, 5.1416636, -5.1416636, -0.08748784, -0.984065, -0.17687361)
(-17.0, 0.96139747, -0.27516335, 10.961397, 4.724837, -10.961397, -0.96139747, -0.6020119, -0.02652102, -0.5503267, -16.343757999999998, -17.0, -49.0, -39.0, 17.0, 11.5, 289.0, -289.0, 578.0, 299.0, 196.0, -4913.0, 4913.0, 4913.0, -9826.0, -14734.0, -3375.0, 6859.0, -4930.0, -4624.0, -5486.0, 17.0, 4.1231055, 17.14643, 1.0371124, 7.0, 85.0, -17.0, 1.2365608000000001, 289.9614, 729.27515, -33.519302, 33.86242, 2.8332132999999997, -0.008547009, 12.833214, 5.1357985, -5.1357985, -0.13227068, -0.96139747, -0.27170414)
(-16.9, 0.929124, -0.36976826, 10.929124, 4.630232, -10.929124, -0.929124, -0.56135184, 0.27148098, -0.7395364999999999, -15.702195999999999, -16.9, -48.7, -38.8, 16.9, 11.45, 285.61, -285.61, 571.22, 295.61, 193.21, -4826.809, 4826.809, 4826.809, -9653.618, -14475.427, -3307.949, 6751.269, -4843.709, -4541.1990000000005, -5393.029, 16.9, 4.110961, 17.047287, 1.0658524999999999, 6.9, 84.5, -16.9, 1.2988923, 286.53912, 723.9798, -33.335438, 33.615116, 2.8273137000000004, -0.00855432, 12.827313, 5.1298985, -5.1298985, -0.17178029, -0.929124, -0.36139938)
(-16.8, 0.88756704, -0.46067858, 10.887567, 4.5393214, -10.887567, -0.88756704, -0.51928866, -0.48235294, -0.92135715, -14.911126000000001, -16.8, -48.4, -38.6, 16.8, 11.4, 282.24, -282.24, 564.48, 292.24, 190.44, -4741.6320000000005, 4741.6320000000005, 4741.6320000000005, -9483.264000000001, -14219.896, -3241.792, 6644.672, -4758.432, -4459.392, -5301.111999999999, 16.8, 4.0987800000000005, 16.948156, 1.0997918, 6.8, 84.0, -16.8, 1.3482456, 283.12756, 718.7007, -33.156216, 33.369659999999996, 2.8213790000000003, -0.008561644, 12.821378999999999, 5.123964, -5.123964, -0.20444156, -0.88756704, -0.44455606)
(-16.7, 0.83714175, -0.546986, 10.837142, 4.453014, -10.837142, -0.83714175, -0.47592753, 0.653157, -1.093972, -13.980267999999999, -16.7, -48.1, -38.4, 16.7, 11.35, 278.89, -278.89, 557.78, 288.89, 187.69, -4657.463, 4657.463, 4657.463, -9314.926, -13967.389, -3176.5229999999997, 6539.203, -4674.163, -4378.573, -5210.2429999999995, 16.7, 4.086563, 16.849035, 1.1363353999999999, 6.7, 83.5, -16.7, 1.3841277, 279.72713999999996, 713.437, -32.981429999999996, 33.126507000000004, 2.8154087000000003, -0.008568981, 12.815408999999999, 5.117994, -5.117994, -0.22895241, -0.83714175, -0.5201153000000001)

In [11]:
train["y1"].values

array([19.794191 , 19.808426 , 19.915476 , 19.715796 , 19.642672 ,
       20.08945  , 19.814774 , 19.566328 , 19.61658  , 19.16017  ,
       18.925045 , 19.205929 , 19.152414 , 18.778013 , 18.648546 ,
       19.094023 , 18.948208 , 18.43834  , 17.865055 , 18.014805 ,
       18.49015  , 17.642826 , 18.280615 , 17.901152 , 17.788818 ,
       17.432823 , 17.78137  , 17.252438 , 17.841944 , 17.175444 ,
       17.400875 , 17.00539  , 17.147802 , 16.76348  , 16.41693  ,
       16.578556 , 16.351282 , 16.108294 , 16.639622 , 16.526445 ,
       16.485176 , 15.990962 , 15.653674 , 15.653441 , 15.816272 ,
       15.527827 , 15.172101 , 15.76198  , 15.317689 , 15.702274 ,
       15.400194 , 15.41707  , 15.386884 , 14.8361225, 14.801024 ,
       14.600244 , 14.278887 , 14.74783  , 14.170936 , 14.209151 ,
       14.018475 , 14.421428 , 13.648277 , 13.659695 , 14.012806 ,
       13.280728 , 13.09564  , 13.820897 , 13.659145 , 13.650429 ,
       13.358913 , 13.008151 , 13.336505 , 13.083289 , 13.193595 ,
       12.360685 , 12.6118355, 12.219076 , 12.855024 , 12.290515 ,
       11.741588 , 11.733461 , 11.971921 , 12.0472355, 12.226347 ,
       11.804474 , 11.622264 , 11.991512 , 11.432112 , 11.280843 ,
       11.234173 , 11.197855 , 11.454589 , 10.626438 , 11.308302 ,
       10.429648 , 10.8849535, 10.45083  , 10.3365965, 10.0118   ,
       10.113633 , 10.632909 ,  9.997225 , 10.102144 ,  9.994061 ,
        9.9856   ,  9.797175 ,  9.756837 ,  9.149104 ,  9.575704 ,
        9.609102 ,  8.7487755,  8.811535 ,  8.490911 ,  8.907814 ,
        8.693342 ,  8.192848 ,  8.443874 ,  8.869007 ,  8.582312 ,
        8.454564 ,  8.192283 ,  8.309404 ,  7.9105062,  7.6680655,
        7.8499513,  7.454269 ,  8.096033 ,  7.2346716,  7.4424763,
        6.949319 ,  6.8056617,  7.277388 ,  7.1082234,  6.850033 ,
        7.150232 ,  7.0554204,  6.268019 ,  6.7529573,  6.53737  ,
        6.0445294,  6.307569 ,  6.092744 ,  5.864985 ,  6.1740184,
        5.4489527,  6.1065955,  6.2040057,  5.742197 ,  5.1052723,
        5.9619226,  5.393327 ,  4.999235 ,  5.621121 ,  4.6354136,
        5.4899435,  4.5712533,  5.043298 ,  4.722965 ,  4.406075 ,
        4.1149573,  4.681517 ,  4.347541 ,  3.9406035,  4.581373 ,
        3.7838426,  3.5889933,  4.2094517,  3.9162698,  4.046211 ,
        3.648476 ,  3.2752087,  4.0102763,  3.416395 ,  3.241523 ,
        3.2260833,  3.6987863,  3.652347 ,  3.1849318,  2.8226717,
        2.9678035,  2.8954964,  3.2667553,  2.749464 ,  2.747597 ,
        2.2453573,  2.4143677,  2.594773 ,  2.4590836,  2.6400878,
        2.8070672,  2.8354099,  2.611497 ,  2.642666 ,  2.4801848,
        1.8825632,  2.0509076,  2.2667134,  2.2886236,  1.9209821,
        1.9067929,  2.5675628,  2.6203866,  2.685984 ,  2.556809 ,
        2.1857252,  2.5973191,  2.6568224,  2.5259166,  2.355599 ,
        2.5227094,  2.4368656,  2.5026953,  2.881026 ,  2.9710875,
        3.08426  ,  3.1883252,  2.7833524,  3.1999373,  2.7145414,
        3.1100483,  3.1710453,  2.7229638,  3.4730835,  3.5808065,
        3.4515193,  3.7003632,  3.2684278,  4.001232 ,  4.0255876,
        3.700993 ,  3.708809 ,  3.4699926,  4.3305583,  3.7323663,
        3.9668567,  4.6750193,  4.1175323,  4.2340584,  4.4459352,
        4.463535 ,  5.032319 ,  4.288235 ,  4.398274 ,  4.632341 ,
        4.6114845,  5.063789 ,  5.4624352,  5.6185317,  5.0919175,
        5.1049514,  5.45758  ,  5.4457574,  5.7090054,  6.251469 ,
        6.104926 ,  6.245378 ,  5.9275246,  6.377687 ,  6.417151 ,
        6.2716055,  6.6624827,  6.9237266,  6.4646153,  6.6074324,
        7.2870946,  7.3306704,  6.847502 ,  7.4591994,  7.744263 ,
        7.5429673,  7.285284 ,  7.293435 ,  7.881856 ,  7.384869 ,
        7.892156 ,  8.295798 ,  7.5499015,  8.496568 ,  8.514796 ,
        8.50117  ,  8.735185 ,  8.304382 ,  8.277512 ,  8.386362 ,
        8.483796 ,  8.64038  ,  9.364765 ,  9.085411 ,  9.539479 ,
        9.355122 ,  9.649523 ,  9.097502 ,  9.988317 ,  9.268267 ,
        9.733954 ,  9.724414 ,  9.788444 , 10.038673 , 10.200377 ,
       10.257575 , 10.112908 ,  9.970628 , 10.819791 , 11.018786 ,
       10.541011 , 11.230107 , 11.4004135, 11.397608 , 10.674099 ,
       11.186346 , 11.190142 , 11.48581  , 11.049973 , 11.571982 ,
       11.424038 , 12.023057 , 11.875231 , 11.541917 , 11.9601345,
       12.121654 , 12.161585 , 12.715348 , 12.64989  , 12.299296 ,
       12.372492 , 12.351159 , 12.407368 , 13.472812 , 12.754487 ,
       13.403902 , 13.180764 , 13.63214  , 13.721045 , 13.744286 ,
       14.1786   , 13.375017 , 13.408315 , 13.887306 , 14.011202 ,
       14.196682 , 14.4814825, 14.019821 , 14.618922 , 14.104806 ,
       14.839924 , 14.9829035, 14.566819 , 14.900892 , 15.119166 ,
       15.432061 , 14.83764  , 15.142854 , 15.345963 , 15.83259  ,
       15.222754 , 15.305669 , 15.625034 , 16.035435 , 16.009762 ,
       15.969356 , 16.744112 , 16.81717  , 16.432932 , 16.834862 ,
       16.37663  , 16.476852 , 17.310276 , 16.593565 , 17.079184 ,
       17.086386 , 16.946707 , 16.948496 , 17.049906 , 17.136465 ,
       17.82894  , 17.643885 , 18.0768   , 17.58586  , 18.51205  ,
       18.222645 , 18.03582  , 18.120226 , 17.992153 , 18.803946 ,
       18.778254 , 18.829569 , 19.12436  , 18.628971 , 18.577003 ,
       19.229618 , 19.368603 , 18.984886 , 19.171904 , 19.178747 ,
       19.450926 , 19.944368 , 20.18959  , 19.973238 , 19.593924 ])

In [12]:
train.y1 = train['y1']
train.y1

x
-20.0    19.794191
-19.9    19.808426
-19.8    19.915476
-19.7    19.715796
-19.6    19.642672
           ...
 19.5    19.450926
 19.6    19.944368
 19.7    20.189590
 19.8    19.973238
 19.9    19.593924
Name: y1, Length: 400, dtype: float64

In [13]:
ideal.y1 = ideal['y1']
ideal.y1

x
-20.0   -0.912945
-19.9   -0.867644
-19.8   -0.813674
-19.7   -0.751573
-19.6   -0.681964
           ...
 19.5    0.605540
 19.6    0.681964
 19.7    0.751573
 19.8    0.813674
 19.9    0.867644
Name: y1, Length: 400, dtype: float64

In [14]:
(train.y1 - ideal.y1)

x
-20.0    20.707136
-19.9    20.676070
-19.8    20.729150
-19.7    20.467369
-19.6    20.324636
           ...
 19.5    18.845386
 19.6    19.262404
 19.7    19.438017
 19.8    19.159564
 19.9    18.726280
Name: y1, Length: 400, dtype: float64

In [15]:
(train.y1 - ideal.y1) ** 2

x
-20.0    428.785494
-19.9    427.499875
-19.8    429.697649
-19.7    418.913212
-19.6    413.090812
            ...
 19.5    355.148579
 19.6    371.040223
 19.7    377.836488
 19.8    367.088903
 19.9    350.673559
Name: y1, Length: 400, dtype: float64

In [16]:
sum((train.y1 - ideal.y1) ** 2)

55511.37465220096

In [17]:
len(train), len(ideal)

(400, 400)

In [18]:
sum((train.y1 - ideal.y1) ** 2) / len(train)

138.7784366305024

In [19]:
ideal.y2

x
-20.0    0.408082
-19.9    0.497186
-19.8    0.581322
-19.7    0.659649
-19.6    0.731386
           ...
 19.5    0.795815
 19.6    0.731386
 19.7    0.659649
 19.8    0.581322
 19.9    0.497186
Name: y2, Length: 400, dtype: float64

In [20]:
sum((train.y1 - ideal.y2) ** 2) / len(train)

136.8677836559274

In [21]:
for i in range(1, 51):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50

In [22]:
MSE0 = []
for i in range(1, 51):
    MSE0.append(sum((train.y1 - ideal.y2) ** 2) / len(train))

In [23]:
MSE0

[136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274,
 136.8677836559274]

In [24]:
n = 5

n = str(n)

type(n)

str

In [25]:
y1 = str("y1")

type(y1)

str

In [26]:
MSE1 = []
for i in range(1, 51):
    i = str(i)
    MSE1.append(sum((train.y1 - ideal["y" + i]) ** 2) / len(train))

In [27]:
MSE1

[138.7784366305024,
 136.8677836559274,
 30.271870112495513,
 58.09341609063414,
 447.07171830409146,
 138.6564462482512,
 141.47162420937786,
 138.63395898765833,
 136.52740868775103,
 214.0957264587692,
 274.12771709923925,
 1307.647518872839,
 806.9291695330389,
 268.9957314766393,
 116.8892021087893,
 28093.710608512592,
 36185.40950006331,
 120051.86115273723,
 30651.949689267556,
 34957.18173805988,
 9144764.651591126,
 9079188.52885468,
 9142826.074238444,
 36576705.34883898,
 82295281.47702985,
 10973288.377894819,
 11169707.416714663,
 9208903.219243946,
 9156720.13547536,
 9309915.753343051,
 0.45968597123930616,
 74.98665130505994,
 0.08056848922483674,
 128.3692016233436,
 108.9206052162392,
 2116.091532704441,
 542.6637626046396,
 141.15780578153016,
 28092.436324993076,
 116913.28239667384,
 676.127772578031,
 665.668758735987,
 94.74758885599724,
 138.4391793383959,
 24.963928294089687,
 60.95535402950792,
 257.9633369971003,
 138.27292350198152,
 139.2449960309114,
 136.96930285653306]

In [28]:
min(MSE1)

0.08056848922483674

In [29]:
MSE1.index(min(MSE1)) + 1

33

In [30]:
MSE1 = []
for i in range(1, 51):
    i = str(i)
    MSE1.append(sum((train.y1 - ideal["y" + i]) ** 2) / len(train))
    
print(MSE1.index(min(MSE1)) + 1)

33

In [31]:
def MSE(train):
    mse = []
    for i in range(1, 51):
        i = str(i)
        mse.append(sum((train - ideal["y" + i]) ** 2) / len(train))
        
    return mse.index(min(mse)) + 1, min(mse)

In [32]:
MSE(train.y1)

(33, 0.08056848922483674)

In [33]:
MSE(train.y2)

(41, 0.08621440844128392)

In [34]:
MSE(train.y3)

(6, 0.08519682325505325)

In [35]:
MSE(train.y4)

(19, 0.07511489956278368)

In [36]:
ideal1 = ideal.y33
ideal2 = ideal.y41
ideal3 = ideal.y6
ideal4 = ideal.y19

In [37]:
ideal1

x
-20.0    20.124610
-19.9    20.025234
-19.8    19.925863
-19.7    19.826498
-19.6    19.727139
           ...
 19.5    19.627787
 19.6    19.727139
 19.7    19.826498
 19.8    19.925863
 19.9    20.025234
Name: y33, Length: 400, dtype: float64

In [38]:
ideal2

x
-20.0   -40.456474
-19.9   -40.233820
-19.8   -40.006836
-19.7   -39.775787
-19.6   -39.540980
           ...
 19.5    39.302770
 19.6    39.540980
 19.7    39.775787
 19.8    40.006836
 19.9    40.233820
Name: y41, Length: 400, dtype: float64

In [39]:
ideal3

x
-20.0    0.912945
-19.9    0.867644
-19.8    0.813674
-19.7    0.751573
-19.6    0.681964
           ...
 19.5   -0.605540
 19.6   -0.681964
 19.7   -0.751573
 19.8   -0.813674
 19.9   -0.867644
Name: y6, Length: 400, dtype: float64

In [40]:
ideal4

x
-20.0    410.00
-19.9    406.01
-19.8    402.04
-19.7    398.09
-19.6    394.16
          ...
 19.5    390.25
 19.6    394.16
 19.7    398.09
 19.8    402.04
 19.9    406.01
Name: y19, Length: 400, dtype: float64

In [41]:
def MSE(train):
    mse = []
    for i in range(1, 51):
        i = str(i)
        mse.append(sum((train - ideal["y" + i]) ** 2) / len(train))
        
    return mse.index(min(mse)) + 1, min(mse)

In [42]:
MSE(train.y1)

(33, 0.08056848922483674)

In [43]:
for i in range(1, 5):
    i = str(i)
    MSE(train["y" + i])

In [44]:
for i in range(1, 5):
    i = str(i)
    print(MSE(train["y" + i]))

(33, 0.08056848922483674)
(41, 0.08621440844128392)
(6, 0.08519682325505325)
(19, 0.07511489956278368)

In [45]:
def MSE_ALL(train):
    mse_all = []
    for i in range(1, 5):
        i = str(i)
        mse_all.append(MSE(train["y" + i]))
    return mse_all

In [46]:
MSE_ALL(train)

[(33, 0.08056848922483674),
 (41, 0.08621440844128392),
 (6, 0.08519682325505325),
 (19, 0.07511489956278368)]

In [47]:
MSE_ALL(train)[0]

(33, 0.08056848922483674)

In [48]:
MSE_ALL(train)[0][0]

33

In [49]:
ideal.y33

x
-20.0    20.124610
-19.9    20.025234
-19.8    19.925863
-19.7    19.826498
-19.6    19.727139
           ...
 19.5    19.627787
 19.6    19.727139
 19.7    19.826498
 19.8    19.925863
 19.9    20.025234
Name: y33, Length: 400, dtype: float64

In [50]:
type(MSE_ALL(train)[0][0])

int

In [51]:
ideal["y" + str(MSE_ALL(train)[0][0])]

x
-20.0    20.124610
-19.9    20.025234
-19.8    19.925863
-19.7    19.826498
-19.6    19.727139
           ...
 19.5    19.627787
 19.6    19.727139
 19.7    19.826498
 19.8    19.925863
 19.9    20.025234
Name: y33, Length: 400, dtype: float64

In [52]:
def Ideal_dataset(train):
    dataset = []
    for i in range(4):
        dataset.append(ideal["y" + str(MSE_ALL(train)[i][0])])
    return dataset

In [53]:
Ideal_dataset(train)

[x
 -20.0    20.124610
 -19.9    20.025234
 -19.8    19.925863
 -19.7    19.826498
 -19.6    19.727139
            ...
  19.5    19.627787
  19.6    19.727139
  19.7    19.826498
  19.8    19.925863
  19.9    20.025234
 Name: y33, Length: 400, dtype: float64,
 x
 -20.0   -40.456474
 -19.9   -40.233820
 -19.8   -40.006836
 -19.7   -39.775787
 -19.6   -39.540980
            ...
  19.5    39.302770
  19.6    39.540980
  19.7    39.775787
  19.8    40.006836
  19.9    40.233820
 Name: y41, Length: 400, dtype: float64,
 x
 -20.0    0.912945
 -19.9    0.867644
 -19.8    0.813674
 -19.7    0.751573
 -19.6    0.681964
            ...
  19.5   -0.605540
  19.6   -0.681964
  19.7   -0.751573
  19.8   -0.813674
  19.9   -0.867644
 Name: y6, Length: 400, dtype: float64,
 x
 -20.0    410.00
 -19.9    406.01
 -19.8    402.04
 -19.7    398.09
 -19.6    394.16
           ...
  19.5    390.25
  19.6    394.16
  19.7    398.09
  19.8    402.04
  19.9    406.01
 Name: y19, Length: 400, dtype: float64]

In [54]:
Ideal_dataset(train)[0]

x
-20.0    20.124610
-19.9    20.025234
-19.8    19.925863
-19.7    19.826498
-19.6    19.727139
           ...
 19.5    19.627787
 19.6    19.727139
 19.7    19.826498
 19.8    19.925863
 19.9    20.025234
Name: y33, Length: 400, dtype: float64

In [55]:
test = pd.read_csv('test.csv', index_col = 0)
test.head()

                y
x
 12.6  257.215420
-14.9    0.267808
-4.5     6.118259
 2.4     5.181103
-17.9   -0.845322

In [56]:
test.sort_index(ascending = True)

                y
x
-19.4   -0.169160
-19.4  214.276120
-19.4  386.796300
-18.7    0.619703
-18.6    0.302509
...           ...
 18.6   94.105940
 18.8  363.701540
 19.0   74.764200
 19.4   77.410530
 19.7   18.980263

[100 rows x 1 columns]

In [57]:
test = pd.read_csv('test.csv')
test.head()

      x           y
0  12.6  257.215420
1 -14.9    0.267808
2  -4.5    6.118259
3   2.4    5.181103
4 -17.9   -0.845322

In [58]:
test.tail(10)

       x           y
90  -6.0  -12.512421
91   7.6   16.806847
92   3.3   20.783113
93 -17.2  -33.632324
94  18.3   18.661032
95   7.3   14.125660
96 -10.0  -25.212278
97 -19.4   -0.169160
98  11.0   22.082275
99  10.4  117.566230

In [59]:
dbname = 'test.db'

conn = sqlite3.connect(dbname)
cur = conn.cursor()

In [60]:
test.to_sql('sample', conn, if_exists = 'replace')

select_sql = 'SELECT * FROM sample'
for row in cur.execute(select_sql):
    print(row)

cur.close()
conn.close()

(0, 12.6, 257.21542)
(1, -14.9, 0.26780778)
(2, -4.5, 6.1182594)
(3, 2.4, 5.181103)
(4, -17.9, -0.8453215000000001)
(5, -12.8, 11.915668)
(6, 16.7, 332.1779)
(7, -7.6, 1.441506)
(8, 2.6, 15.783854000000002)
(9, -15.2, 47.107079999999996)
(10, 16.0, 32.79761)
(11, -14.4, 14.940257)
(12, -14.8, 15.758970000000001)
(13, 19.7, 18.980263)
(14, -19.4, 214.27612000000002)
(15, -3.4, 22.543267999999998)
(16, 1.8, 4.5298676)
(17, -0.9, 2.2496207000000004)
(18, -7.5, 284.7463)
(19, -8.1, 2.2478263)
(20, -2.9, -5.883394200000001)
(21, -3.9, 4.6158123)
(22, 17.5, 2.0819376)
(23, 4.3, 7.5690413)
(24, -5.3, 6.145169)
(25, 8.2, 159.56873000000002)
(26, -17.2, -34.457184000000005)
(27, 19.0, 74.7642)
(28, 3.9, 3.6158087)
(29, 9.2, 9.491855000000001)
(30, 19.4, 77.41053000000001)
(31, 0.5, 384.0741)
(32, -7.0, -0.26300877)
(33, 13.4, 12.927855000000001)
(34, 14.5, 219.86163)
(35, -14.1, 360.32928)
(36, 13.6, -0.35630667)
(37, 7.9, 8.864681)
(38, -3.8, -8.227017)
(39, 15.0, 386.59296)
(40, 0.7, 2.1181924)
(41, 18.2, 10.696613000000001)
(42, -8.7, -17.013218)
(43, -5.7, 56.039469999999994)
(44, 3.6, 22.02443)
(45, 4.9, 2.0495398000000002)
(46, 0.3, 1.7624011999999998)
(47, -15.6, 1.0399175999999999)
(48, -19.4, 386.7963)
(49, -17.7, 324.4076)
(50, -9.7, -18.205744)
(51, -8.3, 2.0187285)
(52, -14.9, -0.47445858)
(53, 7.4, 320.3449)
(54, 13.3, 14.248895000000001)
(55, 18.6, 94.10594)
(56, 18.3, 182.99208000000002)
(57, -12.1, 0.5633795)
(58, 9.1, 89.05603)
(59, 6.5, 52.027786)
(60, -6.6, 8.166065)
(61, -18.7, 0.61970276)
(62, -15.2, 0.14556198)
(63, -18.6, 0.30250879999999997)
(64, -8.0, 8.026902)
(65, 6.4, 0.2627257)
(66, -17.6, 18.138695000000002)
(67, -4.1, 315.02905)
(68, -10.5, 121.47065)
(69, -11.2, 12.678099000000001)
(70, 6.9, 277.00507000000005)
(71, 14.4, 400.78558)
(72, -10.0, 105.32643)
(73, 6.9, 7.5384035)
(74, 11.6, -0.22521149)
(75, -12.0, 153.25531)
(76, -12.7, 0.8070837)
(77, -7.8, 71.15411999999999)
(78, -8.8, -19.02194)
(79, -9.8, 105.45879)
(80, 6.1, 90.71684)
(81, 6.3, 51.05699)
(82, -1.0, 51.278636999999996)
(83, -12.4, -24.845029999999998)
(84, -4.9, -10.347608000000001)
(85, -18.5, 18.017654)
(86, 18.8, 363.70153999999997)
(87, -7.5, 0.027131435)
(88, 0.2, 0.86731744)
(89, -11.6, -2.0795069)
(90, -6.0, -12.512421)
(91, 7.6, 16.806847)
(92, 3.3, 20.783113)
(93, -17.2, -33.632324)
(94, 18.3, 18.661032000000002)
(95, 7.3, 14.12566)
(96, -10.0, -25.212278)
(97, -19.4, -0.1691596)
(98, 11.0, 22.082275)
(99, 10.4, 117.56623)

In [61]:
len(test)

100

In [62]:
test.sort_values(['x'], ascending = True)

       x           y
97 -19.4   -0.169160
14 -19.4  214.276120
48 -19.4  386.796300
61 -18.7    0.619703
63 -18.6    0.302509
..   ...         ...
55  18.6   94.105940
86  18.8  363.701540
27  19.0   74.764200
30  19.4   77.410530
13  19.7   18.980263

[100 rows x 2 columns]

In [63]:
test.sort_values(['x'], ascending = True, inplace = True)

In [64]:
test

       x           y
97 -19.4   -0.169160
14 -19.4  214.276120
48 -19.4  386.796300
61 -18.7    0.619703
63 -18.6    0.302509
..   ...         ...
55  18.6   94.105940
86  18.8  363.701540
27  19.0   74.764200
30  19.4   77.410530
13  19.7   18.980263

[100 rows x 2 columns]

In [65]:
test.reset_index(inplace = True, drop = True)
test

       x           y
0  -19.4   -0.169160
1  -19.4  214.276120
2  -19.4  386.796300
3  -18.7    0.619703
4  -18.6    0.302509
..   ...         ...
95  18.6   94.105940
96  18.8  363.701540
97  19.0   74.764200
98  19.4   77.410530
99  19.7   18.980263

[100 rows x 2 columns]

In [66]:
test.index[0]

0

In [67]:
test[test['x'] == -19.4]

      x          y
0 -19.4   -0.16916
1 -19.4  214.27612
2 -19.4  386.79630

In [68]:
test[test['x'] == -19.4].index[0]

0

In [69]:
test[test['x'] == -19.4].iloc[0]

x   -19.40000
y    -0.16916
Name: 0, dtype: float64

In [70]:
test.iloc[0, 0]

-19.4

In [71]:
test.iloc[0, 1]

-0.1691596

In [72]:
Ideal_dataset(train)[0]

x
-20.0    20.124610
-19.9    20.025234
-19.8    19.925863
-19.7    19.826498
-19.6    19.727139
           ...
 19.5    19.627787
 19.6    19.727139
 19.7    19.826498
 19.8    19.925863
 19.9    20.025234
Name: y33, Length: 400, dtype: float64

In [73]:
Ideal_dataset(train)[0].index[6]

-19.4

In [74]:
Ideal_dataset(train)[0][Ideal_dataset(train)[0].index == -19.4]

x
-19.4    19.52844
Name: y33, dtype: float64

In [75]:
Ideal_dataset(train)[0][Ideal_dataset(train)[0].index == test.iloc[0, 0]]

x
-19.4    19.52844
Name: y33, dtype: float64

In [76]:
Ideal_dataset(train)[0][Ideal_dataset(train)[0].index == -19.4]

x
-19.4    19.52844
Name: y33, dtype: float64

In [77]:
Ideal_dataset(train)[0][-19.4:-19.3]

x
-19.4    19.528440
-19.3    19.429102
Name: y33, dtype: float64

In [78]:
Ideal_dataset(train)[0].iloc[0]

20.12461

In [79]:
Ideal_dataset(train)[0][-19.4:-19.3].iloc[0]

19.52844

In [80]:
Ideal_dataset(train)[0][Ideal_dataset(train)[0].index == test.iloc[0, 0]].iloc[0]

19.52844

In [81]:
Ideal_dataset(train)[0][Ideal_dataset(train)[0].index == test.iloc[0, 0]].iloc[0] \
- test.iloc[0, 1]

19.6975996

In [82]:
Ideal_dataset(train)[1][Ideal_dataset(train)[1].index == test.iloc[0, 0]].iloc[0] \
- test.iloc[0, 1]

-38.8923704

In [83]:
Ideal_dataset(train)[2][Ideal_dataset(train)[2].index == test.iloc[0, 0]].iloc[0] \
- test.iloc[0, 1]

0.69222535

In [84]:
Ideal_dataset(train)[3][Ideal_dataset(train)[3].index == test.iloc[0, 0]].iloc[0] \
- test.iloc[0, 1]

386.5291596

In [85]:
t_0_0 = Ideal_dataset(train)[0][Ideal_dataset(train)[0].index == test.iloc[0, 0]].iloc[0] \
- test.iloc[0, 1]
t_0_0

19.6975996

In [86]:
t_0_1 = Ideal_dataset(train)[1][Ideal_dataset(train)[1].index == test.iloc[0, 0]].iloc[0] \
- test.iloc[0, 1]
t_0_1

-38.8923704

In [87]:
t_0_2 = Ideal_dataset(train)[2][Ideal_dataset(train)[2].index == test.iloc[0, 0]].iloc[0] \
- test.iloc[0, 1]
t_0_2

0.69222535

In [88]:
t_0_3 = Ideal_dataset(train)[3][Ideal_dataset(train)[3].index == test.iloc[0, 0]].iloc[0] \
- test.iloc[0, 1]
t_0_3

386.5291596

In [89]:
min(t_0_0, t_0_1, t_0_2, t_0_3)

-38.8923704

In [90]:
min(t_0_0, t_0_1, t_0_2, t_0_3, key = abs)

0.69222535

In [91]:
[t_0_0, t_0_1, t_0_2, t_0_3][0]

19.6975996

In [92]:
[t_0_0, t_0_1, t_0_2, t_0_3][0] == min(t_0_0, t_0_1, t_0_2, t_0_3, key = abs)

False

In [93]:
[t_0_0, t_0_1, t_0_2, t_0_3][1] == min(t_0_0, t_0_1, t_0_2, t_0_3, key = abs)

False

In [94]:
[t_0_0, t_0_1, t_0_2, t_0_3][2] == min(t_0_0, t_0_1, t_0_2, t_0_3, key = abs)

True

In [95]:
[t_0_0, t_0_1, t_0_2, t_0_3][3] == min(t_0_0, t_0_1, t_0_2, t_0_3, key = abs)

False

In [96]:
[t_0_0, t_0_1, t_0_2, t_0_3].index(min(t_0_0, t_0_1, t_0_2, t_0_3, key = abs))

2

In [97]:
def Test0(train):
    test0 = []
    for i in range(4):
        dev = Ideal_dataset(train)[i][Ideal_dataset(train)[i].index == test.iloc[0, 0]].iloc[0] \
- test.iloc[0, 1]
        test0.append(dev)
    return test0

In [98]:
Test0(train)

[19.6975996, -38.8923704, 0.69222535, 386.5291596]

In [99]:
min([19.6975996, -38.8923704, 0.69222535, 386.5291596], key = abs)

0.69222535

In [100]:
min(Test0(train), key = abs)

0.69222535

In [101]:
def TEST0(train):
    test0 = []
    for i in range(4):
        dev = Ideal_dataset(train)[i][Ideal_dataset(train)[i].index == test.iloc[0, 0]].iloc[0] \
- test.iloc[0, 1]
        test0.append(dev)
        
    test0_min = min(test0, key = abs)
    
    return test0_min

In [102]:
TEST0(train)

0.69222535

In [103]:
def TEST0(train):
    test0 = []
    for i in range(4):
        dev = Ideal_dataset(train)[i][Ideal_dataset(train)[i].index == test.iloc[0, 0]].iloc[0] \
- test.iloc[0, 1]
        test0.append(dev)
        
    test0_min = min(test0, key = abs)
    
    return test0, test0_min

In [104]:
TEST0(train)

([19.6975996, -38.8923704, 0.69222535, 386.5291596], 0.69222535)

In [105]:
[19.6975996, -38.8923704, 0.69222535, 386.5291596].index(0.69222535)

2

In [106]:
def TEST0(train):
    test0 = []
    for i in range(4):
        dev = Ideal_dataset(train)[i][Ideal_dataset(train)[i].index == test.iloc[0, 0]].iloc[0] \
- test.iloc[0, 1]
        test0.append(dev)
        
    test0_min = min(test0, key = abs)
    test0_index = test0.index(test0_min)
    
    return test0_min, test0_index

In [107]:
TEST0(train)

(0.69222535, 2)

In [108]:
t_1_0 = Ideal_dataset(train)[0][Ideal_dataset(train)[0].index == test.iloc[1, 0]].iloc[0] \
- test.iloc[1, 1]
t_1_0

-194.74768000000003

In [109]:
t_1_1 = Ideal_dataset(train)[1][Ideal_dataset(train)[1].index == test.iloc[1, 0]].iloc[0] \
- test.iloc[1, 1]
t_1_1

-253.33765000000002

In [110]:
t_1_2 = Ideal_dataset(train)[2][Ideal_dataset(train)[2].index == test.iloc[1, 0]].iloc[0] \
- test.iloc[1, 1]
t_1_2

-213.75305425000002

In [111]:
t_1_3 = Ideal_dataset(train)[3][Ideal_dataset(train)[3].index == test.iloc[1, 0]].iloc[0] \
- test.iloc[1, 1]
t_1_3

172.08388

In [112]:
min(t_1_0, t_1_1, t_1_2, t_1_3)

-253.33765000000002

In [113]:
min(t_1_0, t_1_1, t_1_2, t_1_3, key 
    = abs)

172.08388

In [114]:
[t_1_0, t_1_1, t_1_2, t_1_3].index(min(t_1_0, t_1_1, t_1_2, t_1_3, key = abs))

3

In [115]:
def TEST1(train):
    test1 = []
    for i in range(4):
        dev = Ideal_dataset(train)[i][Ideal_dataset(train)[i].index == test.iloc[1, 0]].iloc[0] \
- test.iloc[1, 1]
        test1.append(dev)
        
    test1_min = min(test1, key = abs)
    test1_index = test1.index(test1_min)
    
    return test1_min, test1_index

In [116]:
TEST1(train)

(172.08388, 3)

In [117]:
def TEST(train):
    Test = []
    for i in range(4):
        dev = Ideal_dataset(train)[i][Ideal_dataset(train)[i].index == test.iloc[1, 0]].iloc[0] \
- test.iloc[1, 1]
        Test.append(dev)
        
    Test_min = min(Test, key = abs)
    Test_index = Test.index(Test_min)
    
    return Test_min, Test_index

In [118]:
TEST(train)

(172.08388, 3)

In [119]:
def TEST(train, j):
    j = str(j)
    Test = []
    for i in range(4):
        dev = Ideal_dataset(train)[i][Ideal_dataset(train)[i].index == test.iloc[1, 0]].iloc[0] \
- test.iloc[1, 1]
        Test.append(dev)
        
    Test_min = min(Test, key = abs)
    Test_index = Test.index(Test_min)
    
    return Test_min, Test_index

In [120]:
TEST(train, 1)

(172.08388, 3)

In [121]:
def TEST(train, j):
    Test = []
    for i in range(4):
        dev = Ideal_dataset(train)[i][Ideal_dataset(train)[i].index == test.iloc[j, 0]].iloc[0] \
- test.iloc[j, 1]
        Test.append(dev)
        
    Test_min = min(Test, key = abs)
    Test_index = Test.index(Test_min)
    
    return Test_min, Test_index

In [122]:
TEST(train, 0)

(0.69222535, 2)

In [123]:
TEST(train, 0)[0]

0.69222535

In [124]:
TEST(train, 0)[1]

2

In [125]:
TEST(train, 1)

(172.08388, 3)

In [126]:
TEST(train, 1)[0]

172.08388

In [127]:
TEST(train, 0)[1]

2

In [128]:
Test_all_min = []
Test_all_index = []
for i in range(5):
    Test_min = TEST(train, i)[0]
    Test_index = TEST(train, i)[1]
    Test_all_min.append(Test_min)
    Test_all_index.append(Test_index)

In [129]:
Test_all_min

[0.69222535, 172.08388, -0.43629999999996016, -0.76870178, -0.54948246]

In [130]:
Test_all_index

[2, 3, 3, 2, 2]

In [131]:
def TEST_5(train):
    Test_all_min = []
    Test_all_index = []
    for i in range(5):
        Test_min = TEST(train, i)[0]
        Test_index = TEST(train, i)[1]
        Test_all_min.append(Test_min)
        Test_all_index.append(Test_index)
    return Test_all_min, Test_all_index

In [132]:
TEST_5(train)

([0.69222535, 172.08388, -0.43629999999996016, -0.76870178, -0.54948246],
 [2, 3, 3, 2, 2])

In [133]:
TEST_5(train)[0]

[0.69222535, 172.08388, -0.43629999999996016, -0.76870178, -0.54948246]

In [134]:
TEST_5(train)[1]

[2, 3, 3, 2, 2]

In [135]:
def TEST_ALL(train):
    Test_all_min = []
    Test_all_index = []
    for i in range(100):
        Test_min = TEST(train, i)[0]
        Test_index = TEST(train, i)[1]
        Test_all_min.append(Test_min)
        Test_all_index.append(Test_index)
    return Test_all_min, Test_all_index

In [136]:
TEST_ALL(train)

([0.69222535,
  172.08388,
  -0.43629999999996016,
  -0.76870178,
  -0.54948246,
  0.6169910000000023,
  0.032164360000000114,
  -1.1175999999999817,
  -0.39721899999999977,
  0.5556340000000048,
  -0.2692260000000033,
  -0.9321639499999999,
  0.34083672,
  -31.743486999999995,
  1.19733998,
  0.45507362,
  -0.7910040000000009,
  -0.36768049999999874,
  -151.51927999999998,
  1.0781770000000002,
  -0.67385166,
  0.12783299999999898,
  -1.01302696,
  0.7446899999999914,
  1.2566783000000001,
  -1.2570660000000018,
  -1.2206500000000062,
  5.484288000000003,
  4.673569999999998,
  0.5812100000000129,
  -1.0583760000000026,
  1.129482000000003,
  -0.7182670000000009,
  -1.11655665,
  -1.2779364999999996,
  0.27972100000000033,
  -0.3141199999999884,
  -0.47358634999999993,
  0.9108685249999999,
  -218.49630000000002,
  0.91999537,
  -1.1975644,
  0.6521290000000004,
  -13.549469999999992,
  -0.39277799999999985,
  1.0388340000000014,
  -1.093321800000001,
  -288.21905,
  -0.12025879999999933,
  0.9329459999999994,
  -0.9832679999999989,
  -0.03623079999999934,
  -40.278636999999996,
  0.1607734999999999,
  -0.36798278,
  0.4937016000000001,
  -373.8241,
  0.22488240000000026,
  -0.4429439999999998,
  -0.043371400000000726,
  0.976146,
  0.1068870000000004,
  0.935570000000002,
  0.8797448000000005,
  0.5728756999999991,
  -1.0670871700000002,
  -43.506840000000004,
  -1.3669900000000013,
  -0.37927489999999997,
  0.22221400000000102,
  -219.39507000000003,
  -0.2851284999999999,
  0.899557999999999,
  -255.5849,
  -1.1228870000000004,
  -0.6543209999999977,
  -82.32873000000002,
  3.7539699999999954,
  -0.024015000000002118,
  0.5937699999999921,
  -0.5822690000000001,
  1.04804009,
  -88.45542,
  -0.7622350000000004,
  0.6574309999999972,
  -0.5028551300000002,
  -183.42557999999997,
  0.388370000000009,
  -151.59296,
  -0.9415610000000001,
  -43.287900000000036,
  -1.1063115999999997,
  7.640233999999998,
  -146.65323600000002,
  -0.2249260000000035,
  -57.029430000000005,
  -0.26153999999996813,
  -36.68926,
  -38.34900000000001,
  0.8462350000000001],
 [2,
  3,
  3,
  2,
  2,
  0,
  2,
  3,
  0,
  1,
  1,
  2,
  2,
  0,
  2,
  2,
  0,
  0,
  3,
  0,
  2,
  1,
  2,
  3,
  2,
  0,
  3,
  1,
  3,
  3,
  1,
  1,
  1,
  2,
  2,
  0,
  3,
  2,
  2,
  3,
  2,
  0,
  1,
  3,
  0,
  1,
  0,
  3,
  0,
  1,
  3,
  1,
  3,
  0,
  1,
  0,
  3,
  0,
  1,
  1,
  3,
  3,
  3,
  0,
  1,
  2,
  3,
  3,
  2,
  3,
  3,
  0,
  1,
  3,
  1,
  0,
  3,
  3,
  0,
  3,
  1,
  2,
  3,
  0,
  0,
  2,
  3,
  3,
  3,
  1,
  3,
  2,
  0,
  1,
  0,
  1,
  3,
  1,
  1,
  0])

In [137]:
test = pd.read_csv('test.csv')
test.head()

      x           y
0  12.6  257.215420
1 -14.9    0.267808
2  -4.5    6.118259
3   2.4    5.181103
4 -17.9   -0.845322

In [138]:
def TEST(train, j):
    Test = []
    for i in range(4):
        dev = Ideal_dataset(train)[i][Ideal_dataset(train)[i].index == test.iloc[j, 0]].iloc[0] \
- test.iloc[j, 1]
        Test.append(dev)
        
    Test_min = min(Test, key = abs)
    Test_index = Test.index(Test_min)
    
    return Test_min, Test_index

In [139]:
TEST(train, 0)

(-88.45542, 3)

In [140]:
TEST(train, 1)

(0.45507362, 2)

In [141]:
def TEST_5(train):
    Test_all_min = []
    Test_all_index = []
    for i in range(5):
        Test_min = TEST(train, i)[0]
        Test_index = TEST(train, i)[1]
        Test_all_min.append(Test_min)
        Test_all_index.append(Test_index)
    return Test_all_min, Test_all_index

In [142]:
TEST_5(train)

([-88.45542,
  0.45507362,
  -1.093321800000001,
  -0.043371400000000726,
  0.032164360000000114],
 [3, 2, 0, 1, 2])

In [143]:
def TEST_ALL(train):
    Test_all_min = []
    Test_all_index = []
    for i in range(100):
        Test_min = TEST(train, i)[0]
        Test_index = TEST(train, i)[1]
        Test_all_min.append(Test_min)
        Test_all_index.append(Test_index)
    return Test_all_min, Test_all_index

In [144]:
Delta = TEST_ALL(train)[0]
No = TEST_ALL(train)[1]

In [145]:
Delta

[-88.45542,
 0.45507362,
 -1.093321800000001,
 -0.043371400000000726,
 0.032164360000000114,
 1.0781770000000002,
 -43.287900000000036,
 -0.47358634999999993,
 0.976146,
 -31.743486999999995,
 -0.9415610000000001,
 -0.36768049999999874,
 -0.7910040000000009,
 0.8462350000000001,
 172.08388,
 -0.9832679999999989,
 -0.4429439999999998,
 0.1607734999999999,
 -218.49630000000002,
 -1.2779364999999996,
 -0.03623079999999934,
 -0.12025879999999933,
 -1.1063115999999997,
 0.5728756999999991,
 -0.39277799999999985,
 -82.32873000000002,
 0.5556340000000048,
 -36.68926,
 0.8797448000000005,
 -0.024015000000002118,
 -38.34900000000001,
 -373.8241,
 0.91999537,
 0.6574309999999972,
 0.388370000000009,
 -151.51927999999998,
 -0.5028551300000002,
 -0.6543209999999977,
 0.9329459999999994,
 -151.59296,
 0.22488240000000026,
 7.640233999999998,
 -0.7182670000000009,
 -13.549469999999992,
 0.935570000000002,
 -1.0670871700000002,
 0.4937016000000001,
 -0.9321639499999999,
 -0.43629999999996016,
 -1.1175999999999817,
 -1.0583760000000026,
 -1.11655665,
 1.19733998,
 -255.5849,
 -0.7622350000000004,
 -57.029430000000005,
 -146.65323600000002,
 -1.01302696,
 3.7539699999999954,
 0.22221400000000102,
 -1.1975644,
 -0.76870178,
 0.34083672,
 -0.54948246,
 0.27972100000000033,
 -0.37927489999999997,
 -0.39721899999999977,
 -288.21905,
 -1.2206500000000062,
 -1.2570660000000018,
 -219.39507000000003,
 -183.42557999999997,
 4.673569999999998,
 -0.2851284999999999,
 1.04804009,
 0.7446899999999914,
 -0.67385166,
 -0.3141199999999884,
 1.129482000000003,
 0.5812100000000129,
 -43.506840000000004,
 -1.3669900000000013,
 -40.278636999999996,
 0.12783299999999898,
 1.0388340000000014,
 0.6169910000000023,
 -0.26153999999996813,
 0.9108685249999999,
 -0.36798278,
 1.2566783000000001,
 0.6521290000000004,
 -1.1228870000000004,
 0.1068870000000004,
 -0.2692260000000033,
 -0.2249260000000035,
 0.899557999999999,
 5.484288000000003,
 0.69222535,
 -0.5822690000000001,
 0.5937699999999921]

In [146]:
No

[3,
 2,
 0,
 1,
 2,
 0,
 3,
 2,
 3,
 0,
 1,
 0,
 0,
 0,
 3,
 3,
 1,
 0,
 3,
 2,
 1,
 0,
 2,
 1,
 0,
 3,
 1,
 1,
 0,
 0,
 1,
 3,
 2,
 0,
 3,
 3,
 2,
 0,
 1,
 3,
 0,
 0,
 1,
 3,
 3,
 2,
 0,
 2,
 3,
 3,
 1,
 2,
 2,
 3,
 0,
 1,
 1,
 2,
 3,
 3,
 0,
 2,
 2,
 2,
 0,
 2,
 0,
 3,
 3,
 0,
 3,
 3,
 3,
 0,
 2,
 3,
 2,
 3,
 1,
 3,
 3,
 3,
 3,
 1,
 1,
 0,
 3,
 2,
 1,
 2,
 1,
 1,
 3,
 1,
 0,
 1,
 1,
 2,
 1,
 3]

In [147]:
test.insert(2, "Delta Y (test func)", Delta, True)
test

       x           y  Delta Y (test func)
0   12.6  257.215420           -88.455420
1  -14.9    0.267808             0.455074
2   -4.5    6.118259            -1.093322
3    2.4    5.181103            -0.043371
4  -17.9   -0.845322             0.032164
..   ...         ...                  ...
95   7.3   14.125660             0.899558
96 -10.0  -25.212278             5.484288
97 -19.4   -0.169160             0.692225
98  11.0   22.082275            -0.582269
99  10.4  117.566230             0.593770

[100 rows x 3 columns]

In [148]:
test.insert(3, "No. of ideal func", No, True)
test

       x           y  Delta Y (test func)  No. of ideal func
0   12.6  257.215420           -88.455420                  3
1  -14.9    0.267808             0.455074                  2
2   -4.5    6.118259            -1.093322                  0
3    2.4    5.181103            -0.043371                  1
4  -17.9   -0.845322             0.032164                  2
..   ...         ...                  ...                ...
95   7.3   14.125660             0.899558                  1
96 -10.0  -25.212278             5.484288                  1
97 -19.4   -0.169160             0.692225                  2
98  11.0   22.082275            -0.582269                  1
99  10.4  117.566230             0.593770                  3

[100 rows x 4 columns]

In [149]:
test.to_csv('Table 3.csv', header = True, index = False)