In [1]:
import pandas as pd

In [2]:
test = pd.read_csv('Table 3+.csv')
test

,x,y,Delta Y (test func),No. of ideal func,Max. of deviation
0,12.6,257.215420,-88.455420,3,0.445716
1,-14.9,0.267808,0.455074,2,-0.415112
2,-4.5,6.118259,-1.093322,0,0.495927
3,2.4,5.181103,-0.043371,1,0.324352
4,-17.9,-0.845322,0.032164,2,0.396298
...,...,...,...,...,...
95,7.3,14.125660,0.899558,1,-0.247067
96,-10.0,-25.212278,5.484288,1,-0.458306
97,-19.4,-0.169160,0.692225,2,-0.286334
98,11.0,22.082275,-0.582269,1,-0.417487
99,10.4,117.566230,0.593770,3,-0.381117

In [3]:
test.head(100)

,x,y,Delta Y (test func),No. of ideal func,Max. of deviation
0,12.6,257.215420,-88.455420,3,0.445716
1,-14.9,0.267808,0.455074,2,-0.415112
2,-4.5,6.118259,-1.093322,0,0.495927
3,2.4,5.181103,-0.043371,1,0.324352
4,-17.9,-0.845322,0.032164,2,0.396298
...,...,...,...,...,...
95,7.3,14.125660,0.899558,1,-0.247067
96,-10.0,-25.212278,5.484288,1,-0.458306
97,-19.4,-0.169160,0.692225,2,-0.286334
98,11.0,22.082275,-0.582269,1,-0.417487
99,10.4,117.566230,0.593770,3,-0.381117

In [4]:
pd.get_option("display.max_columns")

20

In [5]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
test

,x,y,Delta Y (test func),No. of ideal func,Max. of deviation
0,12.6,257.215420,-88.455420,3,0.445716
1,-14.9,0.267808,0.455074,2,-0.415112
2,-4.5,6.118259,-1.093322,0,0.495927
3,2.4,5.181103,-0.043371,1,0.324352
4,-17.9,-0.845322,0.032164,2,0.396298
5,-12.8,11.915668,1.078177,0,-0.355093
6,16.7,332.177900,-43.287900,3,-0.461241
7,-7.6,1.441506,-0.473586,2,-0.269144
8,2.6,15.783854,0.976146,3,-0.479358
9,-15.2,47.107080,-31.743487,0,-0.425950
10,16.0,32.797610,-0.941561,1,0.468977
11,-14.4,14.940257,-0.367680,0,0.461470
12,-14.8,15.758970,-0.791004,0,-0.418918
13,19.7,18.980263,0.846235,0,-0.363092
14,-19.4,214.276120,172.083880,3,-0.286334
15,-3.4,22.543268,-0.983268,3,0.480405
16,1.8,4.529868,-0.442944,1,-0.411364
17,-0.9,2.249621,0.160773,0,-0.425016
18,-7.5,284.746300,-218.496300,3,0.494952
19,-8.1,2.247826,-1.277936,2,-0.432970
20,-2.9,-5.883394,-0.036231,1,0.386758
21,-3.9,4.615812,-0.120259,0,-0.448276
22,17.5,2.081938,-1.106312,2,-0.416612
23,4.3,7.569041,0.572876,1,0.448374
24,-5.3,6.145169,-0.392778,0,-0.451615
25,8.2,159.568730,-82.328730,3,0.479352
26,-17.2,-34.457184,0.555634,1,-0.497204
27,19.0,74.764200,-36.689260,1,-0.236590
28,3.9,3.615809,0.879745,0,-0.338851
29,9.2,9.491855,-0.024015,0,-0.388227
30,19.4,77.410530,-38.349000,1,0.349693
31,0.5,384.074100,-373.824100,3,-0.383150
32,-7.0,-0.263009,0.919995,2,0.399150
33,13.4,12.927855,0.657431,0,0.381510
34,14.5,219.861630,0.388370,3,0.492642
35,-14.1,360.329280,-151.519280,3,0.461732
36,13.6,-0.356307,-0.502855,2,0.427540
37,7.9,8.864681,-0.654321,0,-0.383010
38,-3.8,-8.227017,0.932946,1,0.446149
39,15.0,386.592960,-151.592960,3,-0.266310
40,0.7,2.118192,0.224882,0,-0.313748
41,18.2,10.696613,7.640234,0,0.430060
42,-8.7,-17.013218,-0.718267,1,0.491850
43,-5.7,56.039470,-13.549470,3,-0.403348
44,3.6,22.024430,0.935570,3,-0.447677
45,4.9,2.049540,-1.067087,2,0.294175
46,0.3,1.762401,0.493702,0,-0.429881
47,-15.6,1.039918,-0.932164,2,-0.485801
48,-19.4,386.796300,-0.436300,3,-0.286334
49,-17.7,324.407600,-1.117600,3,-0.409341
50,-9.7,-18.205744,-1.058376,1,-0.437346
51,-8.3,2.018728,-1.116557,2,-0.322304
52,-14.9,-0.474459,1.197340,2,-0.415112
53,7.4,320.344900,-255.584900,3,-0.455113
54,13.3,14.248895,-0.762235,0,0.365970
55,18.6,94.105940,-57.029430,1,0.467570
56,18.3,182.992080,-146.653236,1,0.443953
57,-12.1,0.563380,-1.013027,2,0.485371
58,9.1,89.056030,3.753970,3,-0.278824
59,6.5,52.027786,0.222214,3,-0.413231
60,-6.6,8.166065,-1.197564,0,0.282250
61,-18.7,0.619703,-0.768702,2,-0.354194
62,-15.2,0.145562,0.340837,2,-0.425950
63,-18.6,0.302509,-0.549482,2,0.265142
64,-8.0,8.026902,0.279721,0,0.392450
65,6.4,0.262726,-0.379275,2,-0.428879
66,-17.6,18.138695,-0.397219,0,0.400767
67,-4.1,315.029050,-288.219050,3,-0.355058
68,-10.5,121.470650,-1.220650,3,0.305807
69,-11.2,12.678099,-1.257066,0,0.497240
70,6.9,277.005070,-219.395070,3,-0.490988
71,14.4,400.785580,-183.425580,3,0.467771
72,-10.0,105.326430,4.673570,3,-0.458306
73,6.9,7.538404,-0.285128,0,-0.490988
74,11.6,-0.225211,1.048040,2,-0.316830
75,-12.0,153.255310,0.744690,3,0.464967
76,-12.7,0.807084,-0.673852,2,-0.450188
77,-7.8,71.154120,-0.314120,3,-0.400910
78,-8.8,-19.021940,1.129482,1,-0.445358
79,-9.8,105.458790,0.581210,3,-0.418420
80,6.1,90.716840,-43.506840,3,-0.351822
81,6.3,51.056990,-1.366990,3,0.487151
82,-1.0,51.278637,-40.278637,3,-0.420032
83,-12.4,-24.845030,0.127833,1,-0.228982
84,-4.9,-10.347608,1.038834,1,-0.408693
85,-18.5,18.017654,0.616991,0,-0.459378
86,18.8,363.701540,-0.261540,3,0.303541
87,-7.5,0.027131,0.910869,2,0.494952
88,0.2,0.867317,-0.367983,1,-0.431470
89,-11.6,-2.079507,1.256678,2,-0.412795
90,-6.0,-12.512421,0.652129,1,0.447253
91,7.6,16.806847,-1.122887,1,0.437986
92,3.3,20.783113,0.106887,3,-0.344332
93,-17.2,-33.632324,-0.269226,1,-0.497204
94,18.3,18.661032,-0.224926,0,0.443953
95,7.3,14.125660,0.899558,1,-0.247067
96,-10.0,-25.212278,5.484288,1,-0.458306
97,-19.4,-0.169160,0.692225,2,-0.286334
98,11.0,22.082275,-0.582269,1,-0.417487
99,10.4,117.566230,0.593770,3,-0.381117

In [6]:
test.iloc[:, 2], test.iloc[:, 4]

(0     -88.455420
 1       0.455074
 2      -1.093322
 3      -0.043371
 4       0.032164
 5       1.078177
 6     -43.287900
 7      -0.473586
 8       0.976146
 9     -31.743487
 10     -0.941561
 11     -0.367680
 12     -0.791004
 13      0.846235
 14    172.083880
 15     -0.983268
 16     -0.442944
 17      0.160773
 18   -218.496300
 19     -1.277936
 20     -0.036231
 21     -0.120259
 22     -1.106312
 23      0.572876
 24     -0.392778
 25    -82.328730
 26      0.555634
 27    -36.689260
 28      0.879745
 29     -0.024015
 30    -38.349000
 31   -373.824100
 32      0.919995
 33      0.657431
 34      0.388370
 35   -151.519280
 36     -0.502855
 37     -0.654321
 38      0.932946
 39   -151.592960
 40      0.224882
 41      7.640234
 42     -0.718267
 43    -13.549470
 44      0.935570
 45     -1.067087
 46      0.493702
 47     -0.932164
 48     -0.436300
 49     -1.117600
 50     -1.058376
 51     -1.116557
 52      1.197340
 53   -255.584900
 54     -0.762235
 55    -57.029430
 56   -146.653236
 57     -1.013027
 58      3.753970
 59      0.222214
 60     -1.197564
 61     -0.768702
 62      0.340837
 63     -0.549482
 64      0.279721
 65     -0.379275
 66     -0.397219
 67   -288.219050
 68     -1.220650
 69     -1.257066
 70   -219.395070
 71   -183.425580
 72      4.673570
 73     -0.285128
 74      1.048040
 75      0.744690
 76     -0.673852
 77     -0.314120
 78      1.129482
 79      0.581210
 80    -43.506840
 81     -1.366990
 82    -40.278637
 83      0.127833
 84      1.038834
 85      0.616991
 86     -0.261540
 87      0.910869
 88     -0.367983
 89      1.256678
 90      0.652129
 91     -1.122887
 92      0.106887
 93     -0.269226
 94     -0.224926
 95      0.899558
 96      5.484288
 97      0.692225
 98     -0.582269
 99      0.593770
 Name: Delta Y (test func), dtype: float64,
 0     0.445716
 1    -0.415112
 2     0.495927
 3     0.324352
 4     0.396298
 5    -0.355093
 6    -0.461241
 7    -0.269144
 8    -0.479358
 9    -0.425950
 10    0.468977
 11    0.461470
 12   -0.418918
 13   -0.363092
 14   -0.286334
 15    0.480405
 16   -0.411364
 17   -0.425016
 18    0.494952
 19   -0.432970
 20    0.386758
 21   -0.448276
 22   -0.416612
 23    0.448374
 24   -0.451615
 25    0.479352
 26   -0.497204
 27   -0.236590
 28   -0.338851
 29   -0.388227
 30    0.349693
 31   -0.383150
 32    0.399150
 33    0.381510
 34    0.492642
 35    0.461732
 36    0.427540
 37   -0.383010
 38    0.446149
 39   -0.266310
 40   -0.313748
 41    0.430060
 42    0.491850
 43   -0.403348
 44   -0.447677
 45    0.294175
 46   -0.429881
 47   -0.485801
 48   -0.286334
 49   -0.409341
 50   -0.437346
 51   -0.322304
 52   -0.415112
 53   -0.455113
 54    0.365970
 55    0.467570
 56    0.443953
 57    0.485371
 58   -0.278824
 59   -0.413231
 60    0.282250
 61   -0.354194
 62   -0.425950
 63    0.265142
 64    0.392450
 65   -0.428879
 66    0.400767
 67   -0.355058
 68    0.305807
 69    0.497240
 70   -0.490988
 71    0.467771
 72   -0.458306
 73   -0.490988
 74   -0.316830
 75    0.464967
 76   -0.450188
 77   -0.400910
 78   -0.445358
 79   -0.418420
 80   -0.351822
 81    0.487151
 82   -0.420032
 83   -0.228982
 84   -0.408693
 85   -0.459378
 86    0.303541
 87    0.494952
 88   -0.431470
 89   -0.412795
 90    0.447253
 91    0.437986
 92   -0.344332
 93   -0.497204
 94    0.443953
 95   -0.247067
 96   -0.458306
 97   -0.286334
 98   -0.417487
 99   -0.381117
 Name: Max. of deviation, dtype: float64)

In [7]:
(test.iloc[:, 2]) ** 2, ((test).iloc[:, 4] ** 2) * 2

(0       7824.361327
 1          0.207092
 2          1.195353
 3          0.001881
 4          0.001035
 5          1.162466
 6       1873.842286
 7          0.224284
 8          0.952861
 9       1007.648967
 10         0.886537
 11         0.135189
 12         0.625687
 13         0.716114
 14     29612.861756
 15         0.966816
 16         0.196199
 17         0.025848
 18     47740.633114
 19         1.633122
 20         0.001313
 21         0.014462
 22         1.223925
 23         0.328187
 24         0.154275
 25      6778.019783
 26         0.308729
 27      1346.101799
 28         0.773951
 29         0.000577
 30      1470.645801
 31    139744.457741
 32         0.846391
 33         0.432216
 34         0.150831
 35     22958.092212
 36         0.252863
 37         0.428136
 38         0.870388
 39     22980.425522
 40         0.050572
 41        58.373176
 42         0.515907
 43       183.588137
 44         0.875291
 45         1.138675
 46         0.243741
 47         0.868930
 48         0.190358
 49         1.249030
 50         1.120160
 51         1.246699
 52         1.433623
 53     65323.641108
 54         0.581002
 55      3252.355886
 56     21507.171629
 57         1.026224
 58        14.092291
 59         0.049379
 60         1.434160
 61         0.590902
 62         0.116170
 63         0.301931
 64         0.078244
 65         0.143849
 66         0.157783
 67     83070.220783
 68         1.489986
 69         1.580215
 70     48134.196740
 71     33644.943398
 72        21.842257
 73         0.081298
 74         1.098388
 75         0.554563
 76         0.454076
 77         0.098671
 78         1.275730
 79         0.337805
 80      1892.845127
 81         1.868662
 82      1622.368599
 83         0.016341
 84         1.079176
 85         0.380678
 86         0.068403
 87         0.829681
 88         0.135411
 89         1.579240
 90         0.425272
 91         1.260875
 92         0.011425
 93         0.072483
 94         0.050592
 95         0.809205
 96        30.077415
 97         0.479176
 98         0.339037
 99         0.352563
 Name: Delta Y (test func), dtype: float64,
 0     0.397326
 1     0.344636
 2     0.491887
 3     0.210409
 4     0.314104
 5     0.252182
 6     0.425487
 7     0.144877
 8     0.459568
 9     0.362867
 10    0.439879
 11    0.425909
 12    0.350985
 13    0.263672
 14    0.163974
 15    0.461577
 16    0.338441
 17    0.361277
 18    0.489955
 19    0.374926
 20    0.299164
 21    0.401903
 22    0.347131
 23    0.402078
 24    0.407912
 25    0.459557
 26    0.494424
 27    0.111950
 28    0.229641
 29    0.301441
 30    0.244570
 31    0.293608
 32    0.318642
 33    0.291099
 34    0.485391
 35    0.426393
 36    0.365581
 37    0.293393
 38    0.398098
 39    0.141843
 40    0.196875
 41    0.369903
 42    0.483833
 43    0.325380
 44    0.400829
 45    0.173078
 46    0.369596
 47    0.472004
 48    0.163974
 49    0.335120
 50    0.382543
 51    0.207759
 52    0.344636
 53    0.414256
 54    0.267868
 55    0.437243
 56    0.394189
 57    0.471171
 58    0.155486
 59    0.341520
 60    0.159330
 61    0.250907
 62    0.362867
 63    0.140601
 64    0.308034
 65    0.367875
 66    0.321228
 67    0.252132
 68    0.187036
 69    0.494495
 70    0.482138
 71    0.437618
 72    0.420089
 73    0.482138
 74    0.200762
 75    0.432389
 76    0.405338
 77    0.321458
 78    0.396687
 79    0.350151
 80    0.247557
 81    0.474632
 82    0.352854
 83    0.104865
 84    0.334060
 85    0.422056
 86    0.184274
 87    0.489955
 88    0.372332
 89    0.340799
 90    0.400070
 91    0.383663
 92    0.237129
 93    0.494424
 94    0.394189
 95    0.122084
 96    0.420089
 97    0.163974
 98    0.348591
 99    0.290500
 Name: Max. of deviation, dtype: float64)

In [8]:
import math
math.sqrt(2)

1.4142135623730951

In [9]:
(test.iloc[:, 2]) ** 2 < ((test).iloc[:, 4] ** 2) * 2

0     False
1      True
2     False
3      True
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15    False
16     True
17     True
18    False
19    False
20     True
21     True
22    False
23     True
24     True
25    False
26     True
27    False
28    False
29     True
30    False
31    False
32    False
33    False
34     True
35    False
36     True
37    False
38    False
39    False
40     True
41    False
42    False
43    False
44    False
45    False
46     True
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
58    False
59     True
60    False
61    False
62     True
63    False
64     True
65     True
66     True
67    False
68    False
69    False
70    False
71    False
72    False
73     True
74    False
75    False
76    False
77     True
78    False
79     True
80    False
81    False
82    False
83     True
84    False
85     True
86     True
87    False
88     True
89    False
90    False
91    False
92     True
93     True
94     True
95    False
96    False
97    False
98     True
99    False
dtype: bool

In [10]:
test[(test.iloc[:, 2]) ** 2 < ((test).iloc[:, 4] ** 2) * 2]

,x,y,Delta Y (test func),No. of ideal func,Max. of deviation
1,-14.9,0.267808,0.455074,2,-0.415112
3,2.4,5.181103,-0.043371,1,0.324352
4,-17.9,-0.845322,0.032164,2,0.396298
11,-14.4,14.940257,-0.367680,0,0.461470
16,1.8,4.529868,-0.442944,1,-0.411364
17,-0.9,2.249621,0.160773,0,-0.425016
20,-2.9,-5.883394,-0.036231,1,0.386758
21,-3.9,4.615812,-0.120259,0,-0.448276
23,4.3,7.569041,0.572876,1,0.448374
24,-5.3,6.145169,-0.392778,0,-0.451615
26,-17.2,-34.457184,0.555634,1,-0.497204
29,9.2,9.491855,-0.024015,0,-0.388227
34,14.5,219.861630,0.388370,3,0.492642
36,13.6,-0.356307,-0.502855,2,0.427540
40,0.7,2.118192,0.224882,0,-0.313748
46,0.3,1.762401,0.493702,0,-0.429881
59,6.5,52.027786,0.222214,3,-0.413231
62,-15.2,0.145562,0.340837,2,-0.425950
64,-8.0,8.026902,0.279721,0,0.392450
65,6.4,0.262726,-0.379275,2,-0.428879
66,-17.6,18.138695,-0.397219,0,0.400767
73,6.9,7.538404,-0.285128,0,-0.490988
77,-7.8,71.154120,-0.314120,3,-0.400910
79,-9.8,105.458790,0.581210,3,-0.418420
83,-12.4,-24.845030,0.127833,1,-0.228982
85,-18.5,18.017654,0.616991,0,-0.459378
86,18.8,363.701540,-0.261540,3,0.303541
88,0.2,0.867317,-0.367983,1,-0.431470
92,3.3,20.783113,0.106887,3,-0.344332
93,-17.2,-33.632324,-0.269226,1,-0.497204
94,18.3,18.661032,-0.224926,0,0.443953
98,11.0,22.082275,-0.582269,1,-0.417487

In [11]:
test_final = test[(test.iloc[:, 2]) ** 2 < ((test).iloc[:, 4] ** 2) * 2]
test_final

,x,y,Delta Y (test func),No. of ideal func,Max. of deviation
1,-14.9,0.267808,0.455074,2,-0.415112
3,2.4,5.181103,-0.043371,1,0.324352
4,-17.9,-0.845322,0.032164,2,0.396298
11,-14.4,14.940257,-0.367680,0,0.461470
16,1.8,4.529868,-0.442944,1,-0.411364
17,-0.9,2.249621,0.160773,0,-0.425016
20,-2.9,-5.883394,-0.036231,1,0.386758
21,-3.9,4.615812,-0.120259,0,-0.448276
23,4.3,7.569041,0.572876,1,0.448374
24,-5.3,6.145169,-0.392778,0,-0.451615
26,-17.2,-34.457184,0.555634,1,-0.497204
29,9.2,9.491855,-0.024015,0,-0.388227
34,14.5,219.861630,0.388370,3,0.492642
36,13.6,-0.356307,-0.502855,2,0.427540
40,0.7,2.118192,0.224882,0,-0.313748
46,0.3,1.762401,0.493702,0,-0.429881
59,6.5,52.027786,0.222214,3,-0.413231
62,-15.2,0.145562,0.340837,2,-0.425950
64,-8.0,8.026902,0.279721,0,0.392450
65,6.4,0.262726,-0.379275,2,-0.428879
66,-17.6,18.138695,-0.397219,0,0.400767
73,6.9,7.538404,-0.285128,0,-0.490988
77,-7.8,71.154120,-0.314120,3,-0.400910
79,-9.8,105.458790,0.581210,3,-0.418420
83,-12.4,-24.845030,0.127833,1,-0.228982
85,-18.5,18.017654,0.616991,0,-0.459378
86,18.8,363.701540,-0.261540,3,0.303541
88,0.2,0.867317,-0.367983,1,-0.431470
92,3.3,20.783113,0.106887,3,-0.344332
93,-17.2,-33.632324,-0.269226,1,-0.497204
94,18.3,18.661032,-0.224926,0,0.443953
98,11.0,22.082275,-0.582269,1,-0.417487

In [12]:
train = pd.read_csv('train.csv', index_col = 0)
train.head()

              y1         y2        y3         y4
x
-20.0  19.794191 -40.422230  1.089534  409.53973
-19.9  19.808426 -40.516800  0.800835  405.70517
-19.8  19.915476 -39.584960  1.095554  401.80957
-19.7  19.715796 -39.989166  1.161140  397.87543
-19.6  19.642672 -39.418360  0.365370  394.22790

In [13]:
ideal = pd.read_csv('ideal.csv', index_col = 0)
ideal.head()

,y1,y2,y3,y4,y5,y6,y7,y8,y9,y10,y11,y12,y13,y14,y15,y16,y17,y18,y19,y20,y21,y22,y23,y24,y25,y26,y27,y28,y29,y30,y31,y32,y33,y34,y35,y36,y37,y38,y39,y40,y41,y42,y43,y44,y45,y46,y47,y48,y49,y50
x,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
-20.0,-0.912945,0.408082,9.087055,5.408082,-9.087055,0.912945,-0.839071,-0.850919,0.816164,18.258905,-20.0,-58.0,-45.0,20.0,13.00,400.00,-400.00,800.00,410.00,289.00,-8000.000,8000.000,8000.000,-16000.000,-23995.000,-5832.000,10648.000,-8020.000,-7600.000,-8795.000,20.0,4.472136,20.124610,-0.746414,10.0,100.0,-20.0,-1.321027,399.08707,899.59190,-40.456474,40.204040,2.995732,-0.008333,12.995732,5.298317,-5.298317,-0.186278,0.912945,0.396850
-19.9,-0.867644,0.497186,9.132356,5.497186,-9.132356,0.867644,-0.865213,0.168518,0.994372,17.266117,-19.9,-57.7,-44.8,19.9,12.95,396.01,-396.01,792.02,406.01,285.61,-7880.599,7880.599,7880.599,-15761.198,-23636.797,-5735.339,10503.459,-7900.499,-7484.589,-8667.619,19.9,4.460942,20.025234,-0.620450,9.9,99.5,-19.9,-1.364830,395.14236,893.51280,-40.233820,40.048590,2.990720,-0.008340,12.990720,5.293305,-5.293305,-0.215690,0.867644,0.476954
-19.8,-0.813674,0.581322,9.186326,5.581322,-9.186326,0.813674,-0.889191,0.612391,1.162644,16.110740,-19.8,-57.4,-44.6,19.8,12.90,392.04,-392.04,784.08,402.04,282.24,-7762.392,7762.392,7762.392,-15524.784,-23282.176,-5639.752,10360.232,-7782.192,-7370.352,-8541.472,19.8,4.449719,19.925863,-0.475739,9.8,99.0,-19.8,-1.394996,391.22632,887.45870,-40.006836,39.890660,2.985682,-0.008347,12.985682,5.288267,-5.288267,-0.236503,0.813674,0.549129
-19.7,-0.751573,0.659649,9.248426,5.659649,-9.248426,0.751573,-0.910947,-0.994669,1.319299,14.805996,-19.7,-57.1,-44.4,19.7,12.85,388.09,-388.09,776.18,398.09,278.89,-7645.373,7645.373,7645.373,-15290.746,-22931.120,-5545.233,10218.313,-7665.073,-7257.283,-8416.553,19.7,4.438468,19.826498,-0.316436,9.7,98.5,-19.7,-1.411223,387.33844,881.43036,-39.775787,39.729824,2.980619,-0.008354,12.980619,5.283204,-5.283204,-0.247887,0.751573,0.612840
-19.6,-0.681964,0.731386,9.318036,5.731386,-9.318036,0.681964,-0.930426,0.774356,1.462772,13.366487,-19.6,-56.8,-44.2,19.6,12.80,384.16,-384.16,768.32,394.16,275.56,-7529.536,7529.536,7529.536,-15059.072,-22583.607,-5451.776,10077.696,-7549.136,-7145.376,-8292.856,19.6,4.427189,19.727139,-0.147038,9.6,98.0,-19.6,-1.413350,383.47803,875.42860,-39.540980,39.565693,2.975530,-0.008361,12.975530,5.278115,-5.278115,-0.249389,0.681964,0.667902

In [14]:
def MSE(train):
    mse = []
    for i in range(1, 51):
        i = str(i)
        mse.append(sum((train - ideal["y" + i]) ** 2) / len(train))
        
    return mse.index(min(mse)) + 1, min(mse)

In [15]:
def MSE_ALL(train):
    mse_all = []
    for i in range(1, 5):
        i = str(i)
        mse_all.append(MSE(train["y" + i]))
    
    return mse_all

In [16]:
def Ideal_Dataset(train):
    dataset = []
    for i in range(4):
        dataset.append(ideal["y" + str(MSE_ALL(train)[i][0])])
        
    return dataset

In [17]:
Ideal_Dataset(train)

[x
 -2.000000e+01    20.124610
 -1.990000e+01    20.025234
 -1.980000e+01    19.925863
 -1.970000e+01    19.826498
 -1.960000e+01    19.727139
 -1.950000e+01    19.627787
 -1.940000e+01    19.528440
 -1.930000e+01    19.429102
 -1.920000e+01    19.329770
 -1.910000e+01    19.230444
 -1.900000e+01    19.131126
 -1.890000e+01    19.031815
 -1.880000e+01    18.932512
 -1.870000e+01    18.833216
 -1.860000e+01    18.733927
 -1.850000e+01    18.634645
 -1.840000e+01    18.535372
 -1.830000e+01    18.436106
 -1.820000e+01    18.336847
 -1.810000e+01    18.237598
 -1.800000e+01    18.138357
 -1.790000e+01    18.039124
 -1.780000e+01    17.939900
 -1.770000e+01    17.840683
 -1.760000e+01    17.741476
 -1.750000e+01    17.642279
 -1.740000e+01    17.543089
 -1.730000e+01    17.443910
 -1.720000e+01    17.344740
 -1.710000e+01    17.245579
 -1.700000e+01    17.146430
 -1.690000e+01    17.047287
 -1.680000e+01    16.948156
 -1.670000e+01    16.849035
 -1.660000e+01    16.749926
 -1.650000e+01    16.650826
 -1.640000e+01    16.551737
 -1.630000e+01    16.452660
 -1.620000e+01    16.353594
 -1.610000e+01    16.254538
 -1.600000e+01    16.155495
 -1.590000e+01    16.056463
 -1.580000e+01    15.957443
 -1.570000e+01    15.858437
 -1.560000e+01    15.759441
 -1.550000e+01    15.660459
 -1.540000e+01    15.561491
 -1.530000e+01    15.462535
 -1.520000e+01    15.363593
 -1.510000e+01    15.264665
 -1.500000e+01    15.165750
 -1.490000e+01    15.066851
 -1.480000e+01    14.967966
 -1.470000e+01    14.869096
 -1.460000e+01    14.770241
 -1.450000e+01    14.671401
 -1.440000e+01    14.572577
 -1.430000e+01    14.473769
 -1.420000e+01    14.374978
 -1.410000e+01    14.276204
 -1.400000e+01    14.177447
 -1.390000e+01    14.078708
 -1.380000e+01    13.979985
 -1.370000e+01    13.881283
 -1.360000e+01    13.782598
 -1.350000e+01    13.683932
 -1.340000e+01    13.585286
 -1.330000e+01    13.486660
 -1.320000e+01    13.388055
 -1.310000e+01    13.289470
 -1.300000e+01    13.190906
 -1.290000e+01    13.092364
 -1.280000e+01    12.993845
 -1.270000e+01    12.895348
 -1.260000e+01    12.796875
 -1.250000e+01    12.698425
 -1.240000e+01    12.600000
 -1.230000e+01    12.501600
 -1.220000e+01    12.403225
 -1.210000e+01    12.304877
 -1.200000e+01    12.206555
 -1.190000e+01    12.108262
 -1.180000e+01    12.009995
 -1.170000e+01    11.911758
 -1.160000e+01    11.813552
 -1.150000e+01    11.715375
 -1.140000e+01    11.617228
 -1.130000e+01    11.519115
 -1.120000e+01    11.421033
 -1.110000e+01    11.322986
 -1.100000e+01    11.224972
 -1.090000e+01    11.126994
 -1.080000e+01    11.029053
 -1.070000e+01    10.931149
 -1.060000e+01    10.833282
 -1.050000e+01    10.735455
 -1.040000e+01    10.637669
 -1.030000e+01    10.539924
 -1.020000e+01    10.442222
 -1.010000e+01    10.344563
 -1.000000e+01    10.246951
 -9.900000e+00    10.149385
 -9.800000e+00    10.051866
 -9.700000e+00     9.954396
 -9.600000e+00     9.856977
 -9.500000e+00     9.759610
 -9.400000e+00     9.662298
 -9.300000e+00     9.565041
 -9.200000e+00     9.467840
 -9.100000e+00     9.370699
 -9.000000e+00     9.273619
 -8.900000e+00     9.176600
 -8.800000e+00     9.079648
 -8.700000e+00     8.982761
 -8.600000e+00     8.885944
 -8.500000e+00     8.789198
 -8.400000e+00     8.692526
 -8.300000e+00     8.595929
 -8.200000e+00     8.499412
 -8.100000e+00     8.402976
 -8.000000e+00     8.306623
 -7.900000e+00     8.210360
 -7.800000e+00     8.114185
 -7.700000e+00     8.018105
 -7.600000e+00     7.922121
 -7.500000e+00     7.826238
 -7.400000e+00     7.730459
 -7.300000e+00     7.634789
 -7.200000e+00     7.539231
 -7.100000e+00     7.443790
 -7.000000e+00     7.348469
 -6.900000e+00     7.253275
 -6.800000e+00     7.158212
 -6.700000e+00     7.063285
 -6.600000e+00     6.968501
 -6.500000e+00     6.873864
 -6.400000e+00     6.779380
 -6.300000e+00     6.685058
 -6.200000e+00     6.590903
 -6.100000e+00     6.496923
 -6.000000e+00     6.403124
 -5.900000e+00     6.309516
 -5.800000e+00     6.216108
 -5.700000e+00     6.122908
 -5.600000e+00     6.029925
 -5.500000e+00     5.937171
 -5.400000e+00     5.844656
 -5.300000e+00     5.752391
 -5.200000e+00     5.660388
 -5.100000e+00     5.568662
 -5.000000e+00     5.477226
 -4.900000e+00     5.386093
 -4.800000e+00     5.295281
 -4.700000e+00     5.204805
 -4.600000e+00     5.114685
 -4.500000e+00     5.024938
 -4.400000e+00     4.935585
 -4.300000e+00     4.846648
 -4.200000e+00     4.758151
 -4.100000e+00     4.670118
 -4.000000e+00     4.582576
 -3.900000e+00     4.495554
 -3.800000e+00     4.409082
 -3.700000e+00     4.323193
 -3.600000e+00     4.237924
 -3.500000e+00     4.153312
 -3.400000e+00     4.069398
 -3.300000e+00     3.986226
 -3.200000e+00     3.903844
 -3.100000e+00     3.822303
 -3.000000e+00     3.741657
 -2.900000e+00     3.661967
 -2.800000e+00     3.583295
 -2.700000e+00     3.505710
 -2.600000e+00     3.429286
 -2.500000e+00     3.354102
 -2.400000e+00     3.280244
 -2.300000e+00     3.207803
 -2.200000e+00     3.136878
 -2.100000e+00     3.067572
 -2.000000e+00     3.000000
 -1.900000e+00     2.934280
 -1.800000e+00     2.870540
 -1.700000e+00     2.808914
 -1.600000e+00     2.749545
 -1.500000e+00     2.692582
 -1.400000e+00     2.638181
 -1.300000e+00     2.586504
 -1.200000e+00     2.537715
 -1.100000e+00     2.491987
 -1.000000e+00     2.449490
 -9.000000e-01     2.410394
 -8.000000e-01     2.374868
 -7.000000e-01     2.343075
 -6.000000e-01     2.315167
 -5.000000e-01     2.291288
 -4.000000e-01     2.271563
 -3.000000e-01     2.256103
 -2.000000e-01     2.244994
 -1.000000e-01     2.238303
  2.842171e-13     2.236068
  1.000000e-01     2.238303
  2.000000e-01     2.244994
  3.000000e-01     2.256103
  4.000000e-01     2.271563
  5.000000e-01     2.291288
  6.000000e-01     2.315167
  7.000000e-01     2.343075
  8.000000e-01     2.374868
  9.000000e-01     2.410394
  1.000000e+00     2.449490
  1.100000e+00     2.491987
  1.200000e+00     2.537715
  1.300000e+00     2.586504
  1.400000e+00     2.638181
  1.500000e+00     2.692582
  1.600000e+00     2.749545
  1.700000e+00     2.808914
  1.800000e+00     2.870540
  1.900000e+00     2.934280
  2.000000e+00     3.000000
  2.100000e+00     3.067572
  2.200000e+00     3.136878
  2.300000e+00     3.207803
  2.400000e+00     3.280244
  2.500000e+00     3.354102
  2.600000e+00     3.429286
  2.700000e+00     3.505710
  2.800000e+00     3.583295
  2.900000e+00     3.661967
  3.000000e+00     3.741657
  3.100000e+00     3.822303
  3.200000e+00     3.903844
  3.300000e+00     3.986226
  3.400000e+00     4.069398
  3.500000e+00     4.153312
  3.600000e+00     4.237924
  3.700000e+00     4.323193
  3.800000e+00     4.409082
  3.900000e+00     4.495554
  4.000000e+00     4.582576
  4.100000e+00     4.670118
  4.200000e+00     4.758151
  4.300000e+00     4.846648
  4.400000e+00     4.935585
  4.500000e+00     5.024938
  4.600000e+00     5.114685
  4.700000e+00     5.204805
  4.800000e+00     5.295281
  4.900000e+00     5.386093
  5.000000e+00     5.477226
  5.100000e+00     5.568662
  5.200000e+00     5.660388
  5.300000e+00     5.752391
  5.400000e+00     5.844656
  5.500000e+00     5.937171
  5.600000e+00     6.029925
  5.700000e+00     6.122908
  5.800000e+00     6.216108
  5.900000e+00     6.309516
  6.000000e+00     6.403124
  6.100000e+00     6.496923
  6.200000e+00     6.590903
  6.300000e+00     6.685058
  6.400000e+00     6.779380
  6.500000e+00     6.873864
  6.600000e+00     6.968501
  6.700000e+00     7.063285
  6.800000e+00     7.158212
  6.900000e+00     7.253275
  7.000000e+00     7.348469
  7.100000e+00     7.443790
  7.200000e+00     7.539231
  7.300000e+00     7.634789
  7.400000e+00     7.730459
  7.500000e+00     7.826238
  7.600000e+00     7.922121
  7.700000e+00     8.018105
  7.800000e+00     8.114185
  7.900000e+00     8.210360
  8.000000e+00     8.306623
  8.100000e+00     8.402976
  8.200000e+00     8.499412
  8.300000e+00     8.595929
  8.400000e+00     8.692526
  8.500000e+00     8.789198
  8.600000e+00     8.885944
  8.700000e+00     8.982761
  8.800000e+00     9.079648
  8.900000e+00     9.176600
  9.000000e+00     9.273619
  9.100000e+00     9.370699
  9.200000e+00     9.467840
  9.300000e+00     9.565041
  9.400000e+00     9.662298
  9.500000e+00     9.759610
  9.600000e+00     9.856977
  9.700000e+00     9.954396
  9.800000e+00    10.051866
  9.900000e+00    10.149385
  1.000000e+01    10.246951
  1.010000e+01    10.344563
  1.020000e+01    10.442222
  1.030000e+01    10.539924
  1.040000e+01    10.637669
  1.050000e+01    10.735455
  1.060000e+01    10.833282
  1.070000e+01    10.931149
  1.080000e+01    11.029053
  1.090000e+01    11.126994
  1.100000e+01    11.224972
  1.110000e+01    11.322986
  1.120000e+01    11.421033
  1.130000e+01    11.519115
  1.140000e+01    11.617228
  1.150000e+01    11.715375
  1.160000e+01    11.813552
  1.170000e+01    11.911758
  1.180000e+01    12.009995
  1.190000e+01    12.108262
  1.200000e+01    12.206555
  1.210000e+01    12.304877
  1.220000e+01    12.403225
  1.230000e+01    12.501600
  1.240000e+01    12.600000
  1.250000e+01    12.698425
  1.260000e+01    12.796875
  1.270000e+01    12.895348
  1.280000e+01    12.993845
  1.290000e+01    13.092364
  1.300000e+01    13.190906
  1.310000e+01    13.289470
  1.320000e+01    13.388055
  1.330000e+01    13.486660
  1.340000e+01    13.585286
  1.350000e+01    13.683932
  1.360000e+01    13.782598
  1.370000e+01    13.881283
  1.380000e+01    13.979985
  1.390000e+01    14.078708
  1.400000e+01    14.177447
  1.410000e+01    14.276204
  1.420000e+01    14.374978
  1.430000e+01    14.473769
  1.440000e+01    14.572577
  1.450000e+01    14.671401
  1.460000e+01    14.770241
  1.470000e+01    14.869096
  1.480000e+01    14.967966
  1.490000e+01    15.066851
  1.500000e+01    15.165750
  1.510000e+01    15.264665
  1.520000e+01    15.363593
  1.530000e+01    15.462535
  1.540000e+01    15.561491
  1.550000e+01    15.660459
  1.560000e+01    15.759441
  1.570000e+01    15.858437
  1.580000e+01    15.957443
  1.590000e+01    16.056463
  1.600000e+01    16.155495
  1.610000e+01    16.254538
  1.620000e+01    16.353594
  1.630000e+01    16.452660
  1.640000e+01    16.551737
  1.650000e+01    16.650826
  1.660000e+01    16.749926
  1.670000e+01    16.849035
  1.680000e+01    16.948156
  1.690000e+01    17.047287
  1.700000e+01    17.146430
  1.710000e+01    17.245579
  1.720000e+01    17.344740
  1.730000e+01    17.443910
  1.740000e+01    17.543089
  1.750000e+01    17.642279
  1.760000e+01    17.741476
  1.770000e+01    17.840683
  1.780000e+01    17.939900
  1.790000e+01    18.039124
  1.800000e+01    18.138357
  1.810000e+01    18.237598
  1.820000e+01    18.336847
  1.830000e+01    18.436106
  1.840000e+01    18.535372
  1.850000e+01    18.634645
  1.860000e+01    18.733927
  1.870000e+01    18.833216
  1.880000e+01    18.932512
  1.890000e+01    19.031815
  1.900000e+01    19.131126
  1.910000e+01    19.230444
  1.920000e+01    19.329770
  1.930000e+01    19.429102
  1.940000e+01    19.528440
  1.950000e+01    19.627787
  1.960000e+01    19.727139
  1.970000e+01    19.826498
  1.980000e+01    19.925863
  1.990000e+01    20.025234
 Name: y33, dtype: float64,
 x
 -2.000000e+01   -4.045647e+01
 -1.990000e+01   -4.023382e+01
 -1.980000e+01   -4.000684e+01
 -1.970000e+01   -3.977579e+01
 -1.960000e+01   -3.954098e+01
 -1.950000e+01   -3.930277e+01
 -1.940000e+01   -3.906153e+01
 -1.930000e+01   -3.881768e+01
 -1.920000e+01   -3.857166e+01
 -1.910000e+01   -3.832392e+01
 -1.900000e+01   -3.807494e+01
 -1.890000e+01   -3.782521e+01
 -1.880000e+01   -3.757523e+01
 -1.870000e+01   -3.732550e+01
 -1.860000e+01   -3.707651e+01
 -1.850000e+01   -3.682876e+01
 -1.840000e+01   -3.658272e+01
 -1.830000e+01   -3.633884e+01
 -1.820000e+01   -3.609758e+01
 -1.810000e+01   -3.585934e+01
 -1.800000e+01   -3.562451e+01
 -1.790000e+01   -3.539342e+01
 -1.780000e+01   -3.516640e+01
 -1.770000e+01   -3.494371e+01
 -1.760000e+01   -3.472558e+01
 -1.750000e+01   -3.451219e+01
 -1.740000e+01   -3.430367e+01
 -1.730000e+01   -3.410011e+01
 -1.720000e+01   -3.390155e+01
 -1.710000e+01   -3.370797e+01
 -1.700000e+01   -3.351930e+01
 -1.690000e+01   -3.333544e+01
 -1.680000e+01   -3.315622e+01
 -1.670000e+01   -3.298143e+01
 -1.660000e+01   -3.281083e+01
 -1.650000e+01   -3.264411e+01
 -1.640000e+01   -3.248095e+01
 -1.630000e+01   -3.232097e+01
 -1.620000e+01   -3.216379e+01
 -1.610000e+01   -3.200897e+01
 -1.600000e+01   -3.185605e+01
 -1.590000e+01   -3.170457e+01
 -1.580000e+01   -3.155405e+01
 -1.570000e+01   -3.140398e+01
 -1.560000e+01   -3.125388e+01
 -1.550000e+01   -3.110323e+01
 -1.540000e+01   -3.095156e+01
 -1.530000e+01   -3.079837e+01
 -1.520000e+01   -3.064320e+01
 -1.510000e+01   -3.048560e+01
 -1.500000e+01   -3.032514e+01
 -1.490000e+01   -3.016144e+01
 -1.480000e+01   -2.999413e+01
 -1.470000e+01   -2.982287e+01
 -1.460000e+01   -2.964740e+01
 -1.450000e+01   -2.946745e+01
 -1.440000e+01   -2.928283e+01
 -1.430000e+01   -2.909339e+01
 -1.420000e+01   -2.889901e+01
 -1.410000e+01   -2.869966e+01
 -1.400000e+01   -2.849530e+01
 -1.390000e+01   -2.828600e+01
 -1.380000e+01   -2.807185e+01
 -1.370000e+01   -2.785298e+01
 -1.360000e+01   -2.762958e+01
 -1.350000e+01   -2.740189e+01
 -1.340000e+01   -2.717019e+01
 -1.330000e+01   -2.693478e+01
 -1.320000e+01   -2.669604e+01
 -1.310000e+01   -2.645433e+01
 -1.300000e+01   -2.621008e+01
 -1.290000e+01   -2.596374e+01
 -1.280000e+01   -2.571575e+01
 -1.270000e+01   -2.546662e+01
 -1.260000e+01   -2.521681e+01
 -1.250000e+01   -2.496684e+01
 -1.240000e+01   -2.471720e+01
 -1.230000e+01   -2.446838e+01
 -1.220000e+01   -2.422089e+01
 -1.210000e+01   -2.397518e+01
 -1.200000e+01   -2.373171e+01
 -1.190000e+01   -2.349093e+01
 -1.180000e+01   -2.325324e+01
 -1.170000e+01   -2.301901e+01
 -1.160000e+01   -2.278859e+01
 -1.150000e+01   -2.256227e+01
 -1.140000e+01   -2.234034e+01
 -1.130000e+01   -2.212299e+01
 -1.120000e+01   -2.191041e+01
 -1.110000e+01   -2.170272e+01
 -1.100000e+01   -2.150001e+01
 -1.090000e+01   -2.130228e+01
 -1.080000e+01   -2.110953e+01
 -1.070000e+01   -2.092168e+01
 -1.060000e+01   -2.073861e+01
 -1.050000e+01   -2.056015e+01
 -1.040000e+01   -2.038609e+01
 -1.030000e+01   -2.021616e+01
 -1.020000e+01   -2.005006e+01
 -1.010000e+01   -1.988746e+01
 -1.000000e+01   -1.972799e+01
 -9.900000e+00   -1.957123e+01
 -9.800000e+00   -1.941676e+01
 -9.700000e+00   -1.926412e+01
 -9.600000e+00   -1.911284e+01
 -9.500000e+00   -1.896242e+01
 -9.400000e+00   -1.881239e+01
 -9.300000e+00   -1.866223e+01
 -9.200000e+00   -1.851144e+01
 -9.100000e+00   -1.835955e+01
 -9.000000e+00   -1.820606e+01
 -8.900000e+00   -1.805051e+01
 -8.800000e+00   -1.789246e+01
 -8.700000e+00   -1.773148e+01
 -8.600000e+00   -1.756720e+01
 -8.500000e+00   -1.739924e+01
 -8.400000e+00   -1.722730e+01
 -8.300000e+00   -1.705109e+01
 -8.200000e+00   -1.687036e+01
 -8.100000e+00   -1.668494e+01
 -8.000000e+00   -1.649468e+01
 -7.900000e+00   -1.629947e+01
 -7.800000e+00   -1.609927e+01
 -7.700000e+00   -1.589408e+01
 -7.600000e+00   -1.568396e+01
 -7.500000e+00   -1.546900e+01
 -7.400000e+00   -1.524935e+01
 -7.300000e+00   -1.502522e+01
 -7.200000e+00   -1.479683e+01
 -7.100000e+00   -1.456449e+01
 -7.000000e+00   -1.432849e+01
 -6.900000e+00   -1.408922e+01
 -6.800000e+00   -1.384706e+01
 -6.700000e+00   -1.360243e+01
 -6.600000e+00   -1.335577e+01
 -6.500000e+00   -1.310756e+01
 -6.400000e+00   -1.285827e+01
 -6.300000e+00   -1.260841e+01
 -6.200000e+00   -1.235846e+01
 -6.100000e+00   -1.210892e+01
 -6.000000e+00   -1.186029e+01
 -5.900000e+00   -1.161306e+01
 -5.800000e+00   -1.136770e+01
 -5.700000e+00   -1.112466e+01
 -5.600000e+00   -1.088437e+01
 -5.500000e+00   -1.064723e+01
 -5.400000e+00   -1.041362e+01
 -5.300000e+00   -1.018387e+01
 -5.200000e+00   -9.958273e+00
 -5.100000e+00   -9.737093e+00
 -5.000000e+00   -9.520538e+00
 -4.900000e+00   -9.308774e+00
 -4.800000e+00   -9.101917e+00
 -4.700000e+00   -8.900039e+00
 -4.600000e+00   -8.703155e+00
 -4.500000e+00   -8.511235e+00
 -4.400000e+00   -8.324199e+00
 -4.300000e+00   -8.141917e+00
 -4.200000e+00   -7.964212e+00
 -4.100000e+00   -7.790862e+00
 -4.000000e+00   -7.621599e+00
 -3.900000e+00   -7.456117e+00
 -3.800000e+00   -7.294071e+00
 -3.700000e+00   -7.135082e+00
 -3.600000e+00   -6.978740e+00
 -3.500000e+00   -6.824608e+00
 -3.400000e+00   -6.672229e+00
 -3.300000e+00   -6.521127e+00
 -3.200000e+00   -6.370813e+00
 -3.100000e+00   -6.220790e+00
 -3.000000e+00   -6.070560e+00
 -2.900000e+00   -5.919625e+00
 -2.800000e+00   -5.767494e+00
 -2.700000e+00   -5.613690e+00
 -2.600000e+00   -5.457751e+00
 -2.500000e+00   -5.299236e+00
 -2.400000e+00   -5.137732e+00
 -2.300000e+00   -4.972853e+00
 -2.200000e+00   -4.804248e+00
 -2.100000e+00   -4.631605e+00
 -2.000000e+00   -4.454649e+00
 -1.900000e+00   -4.273150e+00
 -1.800000e+00   -4.086924e+00
 -1.700000e+00   -3.895832e+00
 -1.600000e+00   -3.699787e+00
 -1.500000e+00   -3.498748e+00
 -1.400000e+00   -3.292725e+00
 -1.300000e+00   -3.081779e+00
 -1.200000e+00   -2.866020e+00
 -1.100000e+00   -2.645604e+00
 -1.000000e+00   -2.420736e+00
 -9.000000e-01   -2.191663e+00
 -8.000000e-01   -1.958678e+00
 -7.000000e-01   -1.722109e+00
 -6.000000e-01   -1.482321e+00
 -5.000000e-01   -1.239713e+00
 -4.000000e-01   -9.947092e-01
 -3.000000e-01   -7.477601e-01
 -2.000000e-01   -4.993347e-01
 -1.000000e-01   -2.499167e-01
  2.842171e-13    7.105427e-13
  1.000000e-01    2.499167e-01
  2.000000e-01    4.993347e-01
  3.000000e-01    7.477601e-01
  4.000000e-01    9.947092e-01
  5.000000e-01    1.239713e+00
  6.000000e-01    1.482321e+00
  7.000000e-01    1.722109e+00
  8.000000e-01    1.958678e+00
  9.000000e-01    2.191663e+00
  1.000000e+00    2.420736e+00
  1.100000e+00    2.645604e+00
  1.200000e+00    2.866020e+00
  1.300000e+00    3.081779e+00
  1.400000e+00    3.292725e+00
  1.500000e+00    3.498748e+00
  1.600000e+00    3.699787e+00
  1.700000e+00    3.895832e+00
  1.800000e+00    4.086924e+00
  1.900000e+00    4.273150e+00
  2.000000e+00    4.454649e+00
  2.100000e+00    4.631605e+00
  2.200000e+00    4.804248e+00
  2.300000e+00    4.972853e+00
  2.400000e+00    5.137732e+00
  2.500000e+00    5.299236e+00
  2.600000e+00    5.457751e+00
  2.700000e+00    5.613690e+00
  2.800000e+00    5.767494e+00
  2.900000e+00    5.919625e+00
  3.000000e+00    6.070560e+00
  3.100000e+00    6.220790e+00
  3.200000e+00    6.370813e+00
  3.300000e+00    6.521127e+00
  3.400000e+00    6.672229e+00
  3.500000e+00    6.824608e+00
  3.600000e+00    6.978740e+00
  3.700000e+00    7.135082e+00
  3.800000e+00    7.294071e+00
  3.900000e+00    7.456117e+00
  4.000000e+00    7.621599e+00
  4.100000e+00    7.790862e+00
  4.200000e+00    7.964212e+00
  4.300000e+00    8.141917e+00
  4.400000e+00    8.324199e+00
  4.500000e+00    8.511235e+00
  4.600000e+00    8.703155e+00
  4.700000e+00    8.900039e+00
  4.800000e+00    9.101917e+00
  4.900000e+00    9.308774e+00
  5.000000e+00    9.520538e+00
  5.100000e+00    9.737093e+00
  5.200000e+00    9.958273e+00
  5.300000e+00    1.018387e+01
  5.400000e+00    1.041362e+01
  5.500000e+00    1.064723e+01
  5.600000e+00    1.088437e+01
  5.700000e+00    1.112466e+01
  5.800000e+00    1.136770e+01
  5.900000e+00    1.161306e+01
  6.000000e+00    1.186029e+01
  6.100000e+00    1.210892e+01
  6.200000e+00    1.235846e+01
  6.300000e+00    1.260841e+01
  6.400000e+00    1.285827e+01
  6.500000e+00    1.310756e+01
  6.600000e+00    1.335577e+01
  6.700000e+00    1.360243e+01
  6.800000e+00    1.384706e+01
  6.900000e+00    1.408922e+01
  7.000000e+00    1.432849e+01
  7.100000e+00    1.456449e+01
  7.200000e+00    1.479683e+01
  7.300000e+00    1.502522e+01
  7.400000e+00    1.524935e+01
  7.500000e+00    1.546900e+01
  7.600000e+00    1.568396e+01
  7.700000e+00    1.589408e+01
  7.800000e+00    1.609927e+01
  7.900000e+00    1.629947e+01
  8.000000e+00    1.649468e+01
  8.100000e+00    1.668494e+01

In [18]:
pd.set_option('display.max_rows', 20)
pd.set_option('display.max_columns', 20)

In [19]:
Ideal_Dataset(train)

[x
 -20.0    20.124610
 -19.9    20.025234
 -19.8    19.925863
 -19.7    19.826498
 -19.6    19.727139
            ...
  19.5    19.627787
  19.6    19.727139
  19.7    19.826498
  19.8    19.925863
  19.9    20.025234
 Name: y33, Length: 400, dtype: float64,
 x
 -20.0   -40.456474
 -19.9   -40.233820
 -19.8   -40.006836
 -19.7   -39.775787
 -19.6   -39.540980
            ...
  19.5    39.302770
  19.6    39.540980
  19.7    39.775787
  19.8    40.006836
  19.9    40.233820
 Name: y41, Length: 400, dtype: float64,
 x
 -20.0    0.912945
 -19.9    0.867644
 -19.8    0.813674
 -19.7    0.751573
 -19.6    0.681964
            ...
  19.5   -0.605540
  19.6   -0.681964
  19.7   -0.751573
  19.8   -0.813674
  19.9   -0.867644
 Name: y6, Length: 400, dtype: float64,
 x
 -20.0    410.00
 -19.9    406.01
 -19.8    402.04
 -19.7    398.09
 -19.6    394.16
           ...
  19.5    390.25
  19.6    394.16
  19.7    398.09
  19.8    402.04
  19.9    406.01
 Name: y19, Length: 400, dtype: float64]

In [20]:
Ideal_Dataset(train)[0].name

'y33'

In [21]:
test.iloc[:, 3]

0     3
1     2
2     0
3     1
4     2
     ..
95    1
96    1
97    2
98    1
99    3
Name: No. of ideal func, Length: 100, dtype: int64

In [22]:
test.iloc[:, 3] == 0

0     False
1     False
2      True
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: No. of ideal func, Length: 100, dtype: bool

In [23]:
test.iloc[:, 3].replace([0, 1, 2, 3], [Ideal_Dataset(train)[0].name, Ideal_Dataset(train)[1].name, Ideal_Dataset(train)[2].name, Ideal_Dataset(train)[3].name])

0     y19
1      y6
2     y33
3     y41
4      y6
     ...
95    y41
96    y41
97     y6
98    y41
99    y19
Name: No. of ideal func, Length: 100, dtype: object

In [24]:
test

,x,y,Delta Y (test func),No. of ideal func,Max. of deviation
0,12.6,257.215420,-88.455420,3,0.445716
1,-14.9,0.267808,0.455074,2,-0.415112
2,-4.5,6.118259,-1.093322,0,0.495927
3,2.4,5.181103,-0.043371,1,0.324352
4,-17.9,-0.845322,0.032164,2,0.396298
...,...,...,...,...,...
95,7.3,14.125660,0.899558,1,-0.247067
96,-10.0,-25.212278,5.484288,1,-0.458306
97,-19.4,-0.169160,0.692225,2,-0.286334
98,11.0,22.082275,-0.582269,1,-0.417487
99,10.4,117.566230,0.593770,3,-0.381117

In [25]:
test_final.iloc[:, 3].replace([0, 1, 2, 3], [Ideal_Dataset(train)[0].name, Ideal_Dataset(train)[1].name, Ideal_Dataset(train)[2].name, Ideal_Dataset(train)[3].name])

1      y6
3     y41
4      y6
11    y33
16    y41
     ...
88    y41
92    y19
93    y41
94    y33
98    y41
Name: No. of ideal func, Length: 32, dtype: object

In [26]:
test_final.iloc[:, 3] = test_final.iloc[:, 3].replace([0, 1, 2, 3], [Ideal_Dataset(train)[0].name, Ideal_Dataset(train)[1].name, Ideal_Dataset(train)[2].name, Ideal_Dataset(train)[3].name])
test_final

C:\Users\gokif\anaconda3\lib\site-packages\pandas\core\indexing.py:1745: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

       x          y  Delta Y (test func) No. of ideal func  Max. of deviation
1  -14.9   0.267808             0.455074                y6          -0.415112
3    2.4   5.181103            -0.043371               y41           0.324352
4  -17.9  -0.845322             0.032164                y6           0.396298
11 -14.4  14.940257            -0.367680               y33           0.461470
16   1.8   4.529868            -0.442944               y41          -0.411364
..   ...        ...                  ...               ...                ...
88   0.2   0.867317            -0.367983               y41          -0.431470
92   3.3  20.783113             0.106887               y19          -0.344332
93 -17.2 -33.632324            -0.269226               y41          -0.497204
94  18.3  18.661032            -0.224926               y33           0.443953
98  11.0  22.082275            -0.582269               y41          -0.417487

[32 rows x 5 columns]

In [27]:
test_final.drop(['Max. of deviation'], axis = 1)

       x          y  Delta Y (test func) No. of ideal func
1  -14.9   0.267808             0.455074                y6
3    2.4   5.181103            -0.043371               y41
4  -17.9  -0.845322             0.032164                y6
11 -14.4  14.940257            -0.367680               y33
16   1.8   4.529868            -0.442944               y41
..   ...        ...                  ...               ...
88   0.2   0.867317            -0.367983               y41
92   3.3  20.783113             0.106887               y19
93 -17.2 -33.632324            -0.269226               y41
94  18.3  18.661032            -0.224926               y33
98  11.0  22.082275            -0.582269               y41

[32 rows x 4 columns]

In [28]:
test_final = test_final.drop(['Max. of deviation'], axis = 1)
test_final

       x          y  Delta Y (test func) No. of ideal func
1  -14.9   0.267808             0.455074                y6
3    2.4   5.181103            -0.043371               y41
4  -17.9  -0.845322             0.032164                y6
11 -14.4  14.940257            -0.367680               y33
16   1.8   4.529868            -0.442944               y41
..   ...        ...                  ...               ...
88   0.2   0.867317            -0.367983               y41
92   3.3  20.783113             0.106887               y19
93 -17.2 -33.632324            -0.269226               y41
94  18.3  18.661032            -0.224926               y33
98  11.0  22.082275            -0.582269               y41

[32 rows x 4 columns]

In [29]:
pd.set_option('display.max_rows', 50)
test_final

       x           y  Delta Y (test func) No. of ideal func
1  -14.9    0.267808             0.455074                y6
3    2.4    5.181103            -0.043371               y41
4  -17.9   -0.845322             0.032164                y6
11 -14.4   14.940257            -0.367680               y33
16   1.8    4.529868            -0.442944               y41
17  -0.9    2.249621             0.160773               y33
20  -2.9   -5.883394            -0.036231               y41
21  -3.9    4.615812            -0.120259               y33
23   4.3    7.569041             0.572876               y41
24  -5.3    6.145169            -0.392778               y33
26 -17.2  -34.457184             0.555634               y41
29   9.2    9.491855            -0.024015               y33
34  14.5  219.861630             0.388370               y19
36  13.6   -0.356307            -0.502855                y6
40   0.7    2.118192             0.224882               y33
46   0.3    1.762401             0.493702               y33
59   6.5   52.027786             0.222214               y19
62 -15.2    0.145562             0.340837                y6
64  -8.0    8.026902             0.279721               y33
65   6.4    0.262726            -0.379275                y6
66 -17.6   18.138695            -0.397219               y33
73   6.9    7.538404            -0.285128               y33
77  -7.8   71.154120            -0.314120               y19
79  -9.8  105.458790             0.581210               y19
83 -12.4  -24.845030             0.127833               y41
85 -18.5   18.017654             0.616991               y33
86  18.8  363.701540            -0.261540               y19
88   0.2    0.867317            -0.367983               y41
92   3.3   20.783113             0.106887               y19
93 -17.2  -33.632324            -0.269226               y41
94  18.3   18.661032            -0.224926               y33
98  11.0   22.082275            -0.582269               y41

In [30]:
test_final.to_csv('Table 3 Final.csv', header = True, index = False)

In [31]:
import sqlite3

In [32]:
dbname = 'Table 3.db'

conn = sqlite3.connect(dbname)
cur = conn.cursor()

In [33]:
test_final.to_sql('sample', conn, if_exists = 'replace')

select_sql = 'SELECT * FROM sample'
for row in cur.execute(select_sql):
    print(row)

cur.close()
conn.close()

(1, -14.9, 0.26780778, 0.45507362, 'y6')
(3, 2.4, 5.181103, -0.043371400000000726, 'y41')
(4, -17.9, -0.8453215000000001, 0.03216436000000012, 'y6')
(11, -14.4, 14.940257, -0.3676804999999987, 'y33')
(16, 1.8, 4.5298676, -0.4429439999999998, 'y41')
(17, -0.9, 2.2496207000000004, 0.1607734999999999, 'y33')
(20, -2.9, -5.8833942000000015, -0.03623079999999933, 'y41')
(21, -3.9, 4.6158123, -0.12025879999999932, 'y33')
(23, 4.3, 7.5690413, 0.5728756999999991, 'y41')
(24, -5.3, 6.145169, -0.3927779999999999, 'y33')
(26, -17.2, -34.457184000000005, 0.5556340000000048, 'y41')
(29, 9.2, 9.491855000000001, -0.024015000000002118, 'y33')
(34, 14.5, 219.86163, 0.3883700000000089, 'y19')
(36, 13.6, -0.35630667, -0.5028551300000002, 'y6')
(40, 0.7, 2.1181924, 0.22488240000000026, 'y33')
(46, 0.3, 1.7624011999999998, 0.4937016000000001, 'y33')
(59, 6.5, 52.027786, 0.22221400000000105, 'y19')
(62, -15.2, 0.14556198, 0.34083672, 'y6')
(64, -8.0, 8.026902, 0.27972100000000033, 'y33')
(65, 6.4, 0.2627257, -0.3792749, 'y6')
(66, -17.6, 18.138695000000002, -0.39721899999999977, 'y33')
(73, 6.9, 7.5384035, -0.2851284999999999, 'y33')
(77, -7.8, 71.15411999999998, -0.3141199999999884, 'y19')
(79, -9.8, 105.45879, 0.5812100000000129, 'y19')
(83, -12.4, -24.845029999999998, 0.12783299999999898, 'y41')
(85, -18.5, 18.017654, 0.6169910000000023, 'y33')
(86, 18.8, 363.70153999999997, -0.2615399999999681, 'y19')
(88, 0.2, 0.86731744, -0.36798278, 'y41')
(92, 3.3, 20.783113, 0.1068870000000004, 'y19')
(93, -17.2, -33.632324, -0.2692260000000033, 'y41')
(94, 18.3, 18.661032000000002, -0.2249260000000035, 'y33')
(98, 11.0, 22.082275, -0.5822690000000001, 'y41')

C:\Users\gokif\anaconda3\lib\site-packages\pandas\core\generic.py:2605: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  sql.to_sql(